-- ============================================================
-- Prewarm exercise_bank — M level (magna cum laude).
-- Vocab: 7 topics × 2 batches = 14 batches / 56 exercises
-- Grammar: 6 topics × 2 batches = 12 batches / 48 exercises
-- Total: 26 batches / 104 exercises.
-- Distractors here are near-synonyms and register shifts — M students
-- need to distinguish *nuance*, not just meaning.
-- ============================================================

-- ─── VOCAB · M · general vocabulary ──────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'M', 'general vocabulary', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Su comportamiento resultó sumamente desconcertante' — mitä tarkoittaa 'desconcertante'?","context":"Su comportamiento durante la reunión resultó sumamente desconcertante para todos los presentes.","options":["A) hämmentävä","B) ärsyttävä","C) ikävä","D) outo"],"correct":"A","explanation":"desconcertante = hämmentävä (saa epävarmaksi). irritante = ärsyttävä, desagradable = ikävä, extraño = outo. Näennäissynonyymien erottelu M-tasolla."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'perustella' (muodollisesti)?","context":"Tuvo que justificar su decisión ante todo el consejo de administración.","options":["A) justificar","B) explicar","C) defender","D) razonar"],"correct":"A","explanation":"justificar = perustella (antaa oikeutus). explicar = selittää (yleinen), defender = puolustaa, razonar = päätellä."},
  {"id":3,"type":"gap","question":"Täydennä: 'Las consecuencias de esa decisión resultaron ___ para la empresa.'","context":"Las consecuencias de esa decisión resultaron devastadoras para la empresa y sus empleados.","options":["A) devastadoras","B) malas","C) tristes","D) difíciles"],"correct":"A","explanation":"devastadora = tuhoisa (voimakas M-sana). mala = huono (neutraali), triste = surullinen, difícil = vaikea. Rekisteri ratkaisee."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'imprescindible'?","context":"Para ese puesto es imprescindible dominar al menos dos idiomas.","options":["A) välttämätön","B) hyödyllinen","C) suositeltava","D) toivottava"],"correct":"A","explanation":"imprescindible = välttämätön (ilman tätä ei onnistu). útil = hyödyllinen, recomendable = suositeltava, deseable = toivottava."}
]$json$::jsonb, 1.0),

('vocab', 'M', 'general vocabulary', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Mostró una actitud sorprendentemente conciliadora' — mitä tarkoittaa 'conciliador'?","context":"Mostró una actitud sorprendentemente conciliadora durante el debate televisado.","options":["A) sovitteleva","B) aggressiivinen","C) varovainen","D) ystävällinen"],"correct":"A","explanation":"conciliador = sovitteleva (hakee yhteisymmärrystä). agresivo = aggressiivinen (vastakohta), prudente = varovainen, amable = ystävällinen (liian yleinen)."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'varmistua' (saada varmuus)?","context":"Antes de firmar, quiso cerciorarse de todas las cláusulas del contrato.","options":["A) cerciorarse","B) asegurar","C) verificar","D) comprobar"],"correct":"A","explanation":"cerciorarse de = varmistua jostakin (formaalinen, refleksiivinen). asegurar = vakuuttaa (toiselle), verificar = tarkistaa (virallinen), comprobar = todeta."},
  {"id":3,"type":"gap","question":"Täydennä: 'El acuerdo se alcanzó tras ___ negociaciones.'","context":"El acuerdo se alcanzó tras arduas negociaciones que duraron más de seis meses.","options":["A) arduas","B) difíciles","C) largas","D) complicadas"],"correct":"A","explanation":"arduas = vaivalloiset, uuvuttavat (muodollinen). difíciles = vaikeat (arki), largas = pitkät (vain kesto), complicadas = monimutkaiset."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el desenlace'?","context":"El desenlace de la novela me sorprendió completamente.","options":["A) loppuratkaisu","B) juoni","C) hahmo","D) teema"],"correct":"A","explanation":"el desenlace = loppuratkaisu (kirjallinen termi). la trama = juoni, el personaje = hahmo, el tema = teema."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · M · travel and transport ────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'M', 'travel and transport', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Los turistas saturan las calles del casco antiguo' — mitä tarkoittaa 'saturar'?","context":"Los turistas saturan las calles del casco antiguo durante los meses de verano.","options":["A) täyttää ääriään myöten","B) vierailla","C) kiertää","D) rikkoa"],"correct":"A","explanation":"saturar = täyttää täysin, kyllästää. visitar = vierailla (neutraali), recorrer = kiertää, dañar = rikkoa."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'majoittua' (muodollisesti)?","context":"Los huéspedes se alojaron en un hotel boutique del centro.","options":["A) alojarse","B) quedarse","C) vivir","D) dormir"],"correct":"A","explanation":"alojarse = majoittua (formaalinen, hotellit). quedarse = jäädä (yleinen), vivir = asua (pysyvä), dormir = nukkua."},
  {"id":3,"type":"gap","question":"Täydennä: 'El viaje resultó ser una experiencia ___.'","context":"El viaje a la Patagonia resultó ser una experiencia inolvidable para toda la familia.","options":["A) inolvidable","B) buena","C) bonita","D) larga"],"correct":"A","explanation":"inolvidable = unohtumaton (voimakas M-sana). bueno/bonito = hyvä/kaunis (B-tason sanoja), largo = pitkä (vain kesto)."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'hacer escala'?","context":"El vuelo a Buenos Aires hace escala en São Paulo durante dos horas.","options":["A) tehdä välilasku","B) myöhästyä","C) peruuntua","D) nousta ilmaan"],"correct":"A","explanation":"hacer escala = tehdä välilasku (lentomatkoilla). retrasarse = myöhästyä, cancelarse = peruuntua, despegar = nousta ilmaan."}
]$json$::jsonb, 1.0),

('vocab', 'M', 'travel and transport', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'El sector turístico se ha recuperado notablemente' — mitä tarkoittaa 'notablemente'?","context":"El sector turístico se ha recuperado notablemente tras los años difíciles de la pandemia.","options":["A) huomattavasti","B) hitaasti","C) vähän","D) täysin"],"correct":"A","explanation":"notablemente = huomattavasti (formaalinen). lentamente = hitaasti, poco = vähän, completamente = täysin."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'turistien tulva'?","context":"La afluencia de turistas colapsó las infraestructuras locales.","options":["A) la afluencia de turistas","B) el número de turistas","C) los turistas","D) la gente"],"correct":"A","explanation":"la afluencia = tulva, saapujien määrä (muodollinen). el número = määrä (neutraali), los turistas = turistit (yleinen)."},
  {"id":3,"type":"gap","question":"Täydennä: 'Muchas ciudades han ___ medidas contra el turismo masivo.'","context":"Muchas ciudades han implementado medidas estrictas contra el turismo masivo.","options":["A) implementado","B) hecho","C) puesto","D) empezado"],"correct":"A","explanation":"implementar medidas = toimeenpanna toimenpiteitä (hallinto-kieli). Hacer/poner ovat arkikieltä, empezar ei sovi."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el destino'?","context":"Elegir el destino adecuado es la parte más difícil de planear un viaje.","options":["A) matkakohde","B) kohtalo","C) tavoite","D) lähtöpiste"],"correct":"A","explanation":"el destino = matkakohde (matkailukontekstissa). Sama sana tarkoittaa myös 'kohtaloa' (el destino del héroe), mutta tässä kontekstissa = matkakohde."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · M · health and body ─────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'M', 'health and body', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La ansiedad crónica afecta al rendimiento académico' — mitä tarkoittaa 'crónica'?","context":"La ansiedad crónica afecta al rendimiento académico de muchos estudiantes universitarios.","options":["A) pitkäaikainen","B) äkillinen","C) vakava","D) kausiluonteinen"],"correct":"A","explanation":"crónica = krooninen, pitkäaikainen. aguda = äkillinen/akuutti (vastakohta!), grave = vakava (kesto ei), estacional = kausiluonteinen."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'kärsiä' (sairaudesta)?","context":"Padece una enfermedad rara desde hace años.","options":["A) padecer","B) sufrir","C) tener","D) sentir"],"correct":"A","explanation":"padecer = kärsiä (pitkäaikainen sairaus, formaali). sufrir = kärsiä (yleinen), tener = olla (arki), sentir = tuntea. Médico käyttää 'padecer'."},
  {"id":3,"type":"gap","question":"Täydennä: 'El estrés laboral puede ___ graves problemas de salud.'","context":"El estrés laboral puede provocar graves problemas de salud a largo plazo.","options":["A) provocar","B) hacer","C) traer","D) dar"],"correct":"A","explanation":"provocar problemas = aiheuttaa ongelmia (muodollinen). hacer/traer/dar ovat liian yleisiä M-tason tekstissä."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'sedentario'?","context":"Un estilo de vida sedentario aumenta el riesgo de enfermedades cardiovasculares.","options":["A) liikunnaton","B) kiireinen","C) rauhallinen","D) tasainen"],"correct":"A","explanation":"sedentario = liikunnaton (istuva). ocupado = kiireinen, tranquilo = rauhallinen, estable = tasainen."}
]$json$::jsonb, 1.0),

('vocab', 'M', 'health and body', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Los trastornos alimentarios afectan cada vez a más adolescentes' — mitä tarkoittaa 'el trastorno'?","context":"Los trastornos alimentarios afectan cada vez a más adolescentes españolas y españoles.","options":["A) häiriö","B) sairaus","C) ongelma","D) tapa"],"correct":"A","explanation":"el trastorno = häiriö (lääketieteellinen). la enfermedad = sairaus (yleinen), el problema = ongelma, la costumbre = tapa."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'paraneminen' (sairaudesta)?","context":"La recuperación tras la operación fue más rápida de lo esperado.","options":["A) la recuperación","B) la mejora","C) la cura","D) la curación"],"correct":"A","explanation":"la recuperación = toipuminen (operaatiosta, leikkauksesta). la mejora = parannus (yleinen), la cura = lääke, la curación = parantuminen (hoidon tulos)."},
  {"id":3,"type":"gap","question":"Täydennä: 'Los médicos ___ un diagnóstico preciso tras varias pruebas.'","context":"Los médicos emitieron un diagnóstico preciso tras varias pruebas y análisis.","options":["A) emitieron","B) hicieron","C) dieron","D) escribieron"],"correct":"A","explanation":"emitir un diagnóstico = antaa diagnoosi (virallinen lääketieteen kieli). hacer/dar on liian arkinen M:llä."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el síntoma'?","context":"La fiebre y el dolor de cabeza son síntomas comunes de la gripe.","options":["A) oire","B) syy","C) vaikutus","D) hoito"],"correct":"A","explanation":"el síntoma = oire. la causa = syy, el efecto = vaikutus, el tratamiento = hoito."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · M · society and politics ────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'M', 'society and politics', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La polarización política divide a la sociedad' — mitä tarkoittaa 'la polarización'?","context":"La polarización política divide a la sociedad en dos bandos irreconciliables.","options":["A) jakautuneisuus","B) keskustelu","C) kilpailu","D) eripura"],"correct":"A","explanation":"la polarización = jakautuneisuus (ääripäihin). el debate = keskustelu, la competencia = kilpailu, el desacuerdo = eripura (lievempi)."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'äänestäjä'?","context":"Los electores decidirán el próximo domingo quién será el nuevo presidente.","options":["A) el elector","B) el votante","C) el ciudadano","D) el participante"],"correct":"A","explanation":"el elector = äänestäjä (virallinen termi). el votante on synonyymi mutta arkisempi, el ciudadano = kansalainen (laajempi), el participante = osallistuja."},
  {"id":3,"type":"gap","question":"Täydennä: 'El partido ___ un programa electoral muy ambicioso.'","context":"El partido ha elaborado un programa electoral muy ambicioso para esta campaña.","options":["A) ha elaborado","B) ha hecho","C) ha escrito","D) ha dicho"],"correct":"A","explanation":"elaborar un programa = laatia ohjelma (muodollinen). hacer/escribir ovat liian yleisiä poliittisessa rekisterissä."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el escaño'?","context":"El partido perdió veinte escaños en las últimas elecciones generales.","options":["A) parlamenttipaikka","B) ääni","C) puolue","D) vaalit"],"correct":"A","explanation":"el escaño = parlamenttipaikka (istuinpaikka). el voto = ääni, el partido = puolue, las elecciones = vaalit."}
]$json$::jsonb, 1.0),

('vocab', 'M', 'society and politics', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La reforma pretende erradicar la pobreza extrema' — mitä tarkoittaa 'erradicar'?","context":"La reforma pretende erradicar la pobreza extrema en las zonas rurales del país.","options":["A) kitkeä pois","B) vähentää","C) hallita","D) tutkia"],"correct":"A","explanation":"erradicar = kitkeä pois (kokonaan hävittää). reducir = vähentää (osittainen), controlar = hallita, estudiar = tutkia."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'toimeenpanna' (laki)?","context":"El parlamento aprobó la ley pero todavía no se ha implementado.","options":["A) implementar","B) hacer","C) seguir","D) respetar"],"correct":"A","explanation":"implementar una ley = toimeenpanna laki (hallinto). hacer = tehdä (yleinen), seguir = noudattaa, respetar = kunnioittaa."},
  {"id":3,"type":"gap","question":"Täydennä: 'Los manifestantes ___ la dimisión del ministro.'","context":"Los manifestantes exigieron la dimisión inmediata del ministro tras el escándalo.","options":["A) exigieron","B) pidieron","C) dijeron","D) quisieron"],"correct":"A","explanation":"exigir = vaatia (vahva, muodollinen). pedir = pyytää (lievempi), decir = sanoa (neutraali), querer = haluta."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la brecha salarial'?","context":"La brecha salarial entre hombres y mujeres sigue siendo significativa.","options":["A) palkkakuilu","B) palkka","C) tulo","D) verot"],"correct":"A","explanation":"la brecha salarial = palkkakuilu (sukupuolten välinen). el sueldo = palkka, el ingreso = tulo, los impuestos = verot."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · M · environment and nature ──────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'M', 'environment and nature', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Las emisiones de gases de efecto invernadero aumentan' — mitä tarkoittaa 'gases de efecto invernadero'?","context":"Las emisiones de gases de efecto invernadero aumentan cada año a pesar de los acuerdos internacionales.","options":["A) kasvihuonekaasut","B) happi","C) typpi","D) savu"],"correct":"A","explanation":"gases de efecto invernadero = kasvihuonekaasut (erikoissanasto). el oxígeno = happi, el nitrógeno = typpi, el humo = savu."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'saada aikaan' (muutos)?","context":"Este pequeño cambio puede ocasionar un gran impacto en el medio ambiente.","options":["A) ocasionar","B) hacer","C) crear","D) causar"],"correct":"A","explanation":"ocasionar = saada aikaan (muodollinen). hacer = tehdä (arki), crear = luoda, causar = aiheuttaa (neutraali). Rekisterin valinta tärkeä M:llä."},
  {"id":3,"type":"gap","question":"Täydennä: 'Es urgente ___ medidas para proteger los océanos.'","context":"Es urgente adoptar medidas concretas para proteger los océanos del plástico.","options":["A) adoptar","B) tomar","C) hacer","D) empezar"],"correct":"A","explanation":"adoptar medidas = ottaa käyttöön toimenpiteitä (muodollinen). tomar on synonyymi mutta vähemmän muodollinen, hacer/empezar liian arkisia."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la huella ecológica'?","context":"Reducir nuestra huella ecológica es responsabilidad de todos.","options":["A) hiilijalanjälki","B) ekoalue","C) luonnontila","D) suojelualue"],"correct":"A","explanation":"la huella ecológica = ekologinen jalanjälki. el área ecológica = ekoalue, el estado natural = luonnontila, el área protegida = suojelualue."}
]$json$::jsonb, 1.0),

('vocab', 'M', 'environment and nature', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Los ecosistemas frágiles están en peligro' — mitä tarkoittaa 'frágil'?","context":"Los ecosistemas frágiles de las zonas polares están en peligro por el calentamiento global.","options":["A) haavoittuvainen","B) pieni","C) kaunis","D) harvinainen"],"correct":"A","explanation":"frágil = haavoittuvainen, hauras (ekologiassa). pequeño = pieni, hermoso = kaunis, raro = harvinainen."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'säilyttää' (luonnollinen tila)?","context":"Debemos preservar la biodiversidad para las próximas generaciones.","options":["A) preservar","B) guardar","C) salvar","D) mantener"],"correct":"A","explanation":"preservar = säilyttää luonnontila (muodollinen). guardar = tallettaa, salvar = pelastaa (akuutti), mantener = ylläpitää."},
  {"id":3,"type":"gap","question":"Täydennä: 'La deforestación ___ un ritmo alarmante.'","context":"La deforestación avanza a un ritmo alarmante en la Amazonía brasileña.","options":["A) avanza a","B) va a","C) hace a","D) sale a"],"correct":"A","explanation":"avanzar a un ritmo = edetä tahtia (muodollinen). Tässä verbi + substantiivi -kollokaatio: 'avanzar a ritmo'."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el vertido'?","context":"El vertido accidental de petróleo contaminó kilómetros de costa.","options":["A) valuma","B) tulva","C) myrsky","D) roska"],"correct":"A","explanation":"el vertido = valuma (esim. öljy). la inundación = tulva, la tormenta = myrsky, la basura = roska."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · M · culture and arts ────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'M', 'culture and arts', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La obra aborda temas universales con gran sensibilidad' — mitä tarkoittaa 'abordar'?","context":"La obra aborda temas universales con gran sensibilidad y maestría narrativa.","options":["A) käsitellä","B) aloittaa","C) kirjoittaa","D) valita"],"correct":"A","explanation":"abordar = käsitellä (aihetta). empezar = aloittaa, escribir = kirjoittaa, elegir = valita. 'abordar un tema' on M-tason kiinteä kollokaatio."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'tulkinta' (teos)?","context":"Su interpretación del papel recibió elogios de la crítica.","options":["A) la interpretación","B) la traducción","C) la actuación","D) la explicación"],"correct":"A","explanation":"la interpretación = tulkinta (taideteos). la traducción = käännös, la actuación = esitys, la explicación = selitys."},
  {"id":3,"type":"gap","question":"Täydennä: 'La novela ha sido ___ al inglés y al francés.'","context":"La novela ha sido traducida al inglés y al francés con gran éxito.","options":["A) traducida","B) escrita","C) publicada","D) leída"],"correct":"A","explanation":"traducir al inglés = kääntää englanniksi. Muut verbit vaatisivat eri prepositiot tai merkitykset."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el protagonista'?","context":"El protagonista de la película es un joven escritor que lucha con el bloqueo creativo.","options":["A) päähenkilö","B) sivuhenkilö","C) kertoja","D) antagonisti"],"correct":"A","explanation":"el protagonista = päähenkilö. el personaje secundario = sivuhenkilö, el narrador = kertoja, el antagonista = antagonisti."}
]$json$::jsonb, 1.0),

('vocab', 'M', 'culture and arts', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'El director plasmó perfectamente la atmósfera del libro' — mitä tarkoittaa 'plasmar'?","context":"El director plasmó perfectamente la atmósfera del libro en la adaptación cinematográfica.","options":["A) välittää (taiteellisesti)","B) muokata","C) korvata","D) kuvitella"],"correct":"A","explanation":"plasmar = välittää, tuoda esiin (taiteellisesti). modificar = muokata, reemplazar = korvata, imaginar = kuvitella."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'kritiikki' (taidekritiikki)?","context":"La crítica recibió la exposición con entusiasmo.","options":["A) la crítica","B) la opinión","C) el comentario","D) la queja"],"correct":"A","explanation":"la crítica = taidekritiikki, kriitikot (kollektiivi). la opinión = mielipide, el comentario = kommentti, la queja = valitus."},
  {"id":3,"type":"gap","question":"Täydennä: 'El escultor ___ un estilo único y reconocible.'","context":"El escultor desarrolló un estilo único y reconocible a lo largo de su carrera.","options":["A) desarrolló","B) tuvo","C) hizo","D) compró"],"correct":"A","explanation":"desarrollar un estilo = kehittää tyyli (taiteellinen kehitys). tener = olla (staattinen), hacer = tehdä (yleinen)."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la vanguardia'?","context":"Su obra siempre ha estado a la vanguardia del arte contemporáneo.","options":["A) eturintama","B) kuuluisuus","C) menestys","D) tyyli"],"correct":"A","explanation":"la vanguardia = eturintama, uudistaja. la fama = kuuluisuus, el éxito = menestys, el estilo = tyyli."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · M · work and economy ────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'M', 'work and economy', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La precariedad laboral afecta sobre todo a los jóvenes' — mitä tarkoittaa 'la precariedad'?","context":"La precariedad laboral afecta sobre todo a los jóvenes menores de treinta años.","options":["A) epävarmuus","B) puute","C) kilpailu","D) stressi"],"correct":"A","explanation":"la precariedad = epävarmuus (työsuhteessa). la falta = puute, la competencia = kilpailu, el estrés = stressi."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'irtisanoa' (muodollisesti)?","context":"La empresa despidió a cien empleados por la crisis económica.","options":["A) despedir","B) echar","C) sacar","D) quitar"],"correct":"A","explanation":"despedir = irtisanoa (virallinen). echar/sacar/quitar ovat arkikieltä ja merkitsevät myös muuta. M-tasolla muodollinen termi."},
  {"id":3,"type":"gap","question":"Täydennä: 'Los sindicatos ___ una huelga general para el lunes.'","context":"Los sindicatos han convocado una huelga general para el lunes de la próxima semana.","options":["A) han convocado","B) han hecho","C) han dicho","D) han querido"],"correct":"A","explanation":"convocar una huelga = julistaa lakko (virallinen kieli). hacer/decir ovat liian yleisiä ammattiyhdistyskielessä."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el autónomo'?","context":"Cada vez más profesionales prefieren trabajar como autónomos.","options":["A) itsenäinen yrittäjä","B) vapaaehtoinen","C) harrastelija","D) asiantuntija"],"correct":"A","explanation":"el autónomo = itsenäinen yrittäjä (Espanjassa virallinen termi). el voluntario = vapaaehtoinen, el aficionado = harrastelija, el experto = asiantuntija."}
]$json$::jsonb, 1.0),

('vocab', 'M', 'work and economy', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La economía se estancó durante el segundo trimestre' — mitä tarkoittaa 'estancarse'?","context":"La economía española se estancó durante el segundo trimestre de este año.","options":["A) pysähtyä","B) kasvaa","C) laskea","D) romahtaa"],"correct":"A","explanation":"estancarse = pysähtyä, jäädä paikalleen. crecer = kasvaa, bajar = laskea, derrumbarse = romahtaa. Hieno nyanssi nollakasvun ja laskun välillä."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'neuvotella' (virallisesti)?","context":"Los representantes negociaron las nuevas condiciones del convenio colectivo.","options":["A) negociar","B) hablar","C) discutir","D) acordar"],"correct":"A","explanation":"negociar = neuvotella (virallinen, sopimukset). hablar = puhua, discutir = kiistellä (negatiivinen sävy), acordar = sopia (jo saavutettu sopu)."},
  {"id":3,"type":"gap","question":"Täydennä: 'La empresa ___ un nuevo modelo de negocio más sostenible.'","context":"La empresa ha impulsado un nuevo modelo de negocio más sostenible y ético.","options":["A) ha impulsado","B) ha puesto","C) ha dado","D) ha hecho"],"correct":"A","explanation":"impulsar un modelo = edistää mallia (aktiivisesti, muodollinen). Muut verbit ovat liian yleisiä business-kielessä."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la inflación'?","context":"La inflación alcanzó el ocho por ciento en el último año.","options":["A) inflaatio","B) työttömyys","C) velka","D) verotus"],"correct":"A","explanation":"la inflación = inflaatio. el desempleo = työttömyys, la deuda = velka, la fiscalidad = verotus."}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · M · ser_estar ─────────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'M', 'ser_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'El asunto no ___ tan sencillo como parecía al principio.'","context":"El asunto no es tan sencillo como parecía al principio de las negociaciones.","options":["A) es","B) está","C) hay","D) tiene"],"correct":"A","explanation":"Asian luonteen arviointi (on luonteeltaan yksinkertainen) → ser. Está sencillo tarkoittaisi 'on helppo juuri nyt' (hetkellinen tila).","rule":"ser_evaluacion_asunto"},
  {"id":2,"type":"gap","question":"Täydennä: 'Aunque ___ cansados, decidieron continuar la reunión.'","context":"Aunque estaban cansados, decidieron continuar la reunión hasta encontrar una solución.","options":["A) estaban","B) eran","C) fueron","D) habían"],"correct":"A","explanation":"Tilapäinen väsyminen → estar. 'Eran cansados' tarkoittaisi 'olivat raskaita ihmisinä' (merkityseron huomaaminen M:llä).","rule":"estar_estado_fisico_m"},
  {"id":3,"type":"gap","question":"Täydennä: 'Las conclusiones del informe ___ preocupantes.'","context":"Las conclusiones del informe son preocupantes para el gobierno y la población.","options":["A) son","B) están","C) hay","D) tienen"],"correct":"A","explanation":"Raportin päätelmien luonne (huolestuttavia sisällöltään) → ser preocupantes. Están preocupantes tarkoittaisi 'ovat huolissaan' (paradoksaali).","rule":"ser_caracteristica_abstracta"},
  {"id":4,"type":"gap","question":"Täydennä: 'El edificio ___ construido en el siglo XVIII.'","context":"El edificio fue construido en el siglo XVIII por un arquitecto italiano famoso.","options":["A) fue","B) estuvo","C) era","D) estaba"],"correct":"A","explanation":"Passiivi 'rakennettiin' → ser + participio (preterito). 'Fue construido' = rakennettiin, 'estuvo construido' olisi kielioppivirhe.","rule":"ser_pasiva"}
]$json$::jsonb, 1.0),

('grammar', 'M', 'ser_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'La solución propuesta ___ de lo más interesante.'","context":"La solución propuesta por el equipo es de lo más interesante y creativa.","options":["A) es","B) está","C) hay","D) tiene"],"correct":"A","explanation":"'ser de lo más + adjetiivi' = erittäin (voimakas ilmaus) — vaatii aina ser:n, ei estar:ia.","rule":"ser_de_lo_mas"},
  {"id":2,"type":"gap","question":"Täydennä: 'El resultado ___ claro desde el principio.'","context":"El resultado estaba claro desde el principio de la competición.","options":["A) estaba","B) era","C) fue","D) había"],"correct":"A","explanation":"'estar claro' = on selvää (tilanne on käsitettävissä). 'Ser claro' henkilöstä = ilmaista itsensä selvästi. Tässä tilanne → estar.","rule":"estar_claro_situacion"},
  {"id":3,"type":"gap","question":"Täydennä: 'El libro ___ escrito en un lenguaje muy poético.'","context":"El libro está escrito en un lenguaje muy poético y evocador.","options":["A) está","B) es","C) hay","D) tiene"],"correct":"A","explanation":"Partisiippi lopputuloksena (kirja on kirjoitettuna tässä tyylissä) → estar. 'Es escrito' toimii vain toiminnallisessa passiivissa ('kirja kirjoitetaan').","rule":"estar_participio_estado"},
  {"id":4,"type":"gap","question":"Täydennä: 'Ese comportamiento ___ propio de alguien con mucha experiencia.'","context":"Ese comportamiento es propio de alguien con mucha experiencia profesional.","options":["A) es","B) está","C) hay","D) tiene"],"correct":"A","explanation":"'ser propio de' = ominaista jollekin (pysyvä piirre) — vakiokollokaatio ser:lla. 'estar propio' ei ole olemassa.","rule":"ser_propio_de"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · M · hay_estar ─────────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'M', 'hay_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'En la actualidad ___ numerosos estudios sobre este fenómeno.'","context":"En la actualidad hay numerosos estudios sobre este fenómeno psicológico.","options":["A) hay","B) están","C) son","D) existen"],"correct":"A","explanation":"Olemassaolo (epämäärä lukumäärä, tutkimuksia on olemassa) → hay. 'Están' vaatisi määrätyn viittauksen. 'Existen' toimii mutta hay on yleisempi ja tavallisempi.","rule":"hay_existencia_abstracta"},
  {"id":2,"type":"gap","question":"Täydennä: 'Las oficinas centrales ___ en el distrito financiero de Madrid.'","context":"Las oficinas centrales están ubicadas en el distrito financiero de Madrid.","options":["A) están","B) hay","C) son","D) tienen"],"correct":"A","explanation":"Määrätyn yrityksen pääkonttorin sijainti → estar. 'Hay oficinas' toimisi ilman määräistä artikkelia.","rule":"estar_ubicacion_definida_m"},
  {"id":3,"type":"gap","question":"Täydennä: '___ razones de sobra para preocuparse.'","context":"Hay razones de sobra para preocuparse por la situación económica.","options":["A) Hay","B) Están","C) Son","D) Existen"],"correct":"A","explanation":"Epämääräinen olemassaolo (on syitä) → hay. Kiinteä ilmaus 'hay razones para' + infinitiivi.","rule":"hay_razones_para"},
  {"id":4,"type":"gap","question":"Täydennä: 'El museo ___ abierto de diez a ocho todos los días.'","context":"El museo está abierto de diez a ocho todos los días excepto los lunes.","options":["A) está","B) es","C) hay","D) tiene"],"correct":"A","explanation":"Aukioloaika (tila joka jatkuu) → estar abierto. 'Es abierto' tarkoittaisi henkilöstä 'on avoin/suora' — eri merkitys.","rule":"estar_abierto_horario"}
]$json$::jsonb, 1.0),

('grammar', 'M', 'hay_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'No ___ consenso sobre este tema entre los expertos.'","context":"No hay consenso sobre este tema entre los expertos de la universidad.","options":["A) hay","B) está","C) es","D) tiene"],"correct":"A","explanation":"Abstraktin olemassaolon kieltäminen (ei konsensusta) → hay. 'No está consenso' on kielioppivirhe.","rule":"no_hay_consenso"},
  {"id":2,"type":"gap","question":"Täydennä: 'La sede de la ONU ___ en Nueva York.'","context":"La sede de la ONU está en Nueva York desde su fundación en 1945.","options":["A) está","B) hay","C) es","D) tiene"],"correct":"A","explanation":"Määrätyn (la sede) sijainti → estar. YK:n päämajan paikka on yksilöity → ei koskaan hay.","rule":"estar_sede_ubicacion"},
  {"id":3,"type":"gap","question":"Täydennä: 'En esta ciudad ___ dos museos de arte contemporáneo muy importantes.'","context":"En esta ciudad hay dos museos de arte contemporáneo muy importantes y visitados.","options":["A) hay","B) están","C) son","D) tienen"],"correct":"A","explanation":"Epämääräinen lukumäärä (dos museos) → hay. 'Están los dos museos' vaatisi määräisen artikkelin.","rule":"hay_numero_indefinido"},
  {"id":4,"type":"gap","question":"Täydennä: 'La conferencia ___ prevista para el próximo jueves.'","context":"La conferencia está prevista para el próximo jueves a las seis de la tarde.","options":["A) está","B) es","C) hay","D) tiene"],"correct":"A","explanation":"'estar previsto' = olla suunniteltu (partisiippi + tila) on kiinteä ilmaus. 'Ser previsto' olisi harvinainen muoto.","rule":"estar_previsto"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · M · subjunctive ───────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'M', 'subjunctive', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Es probable que ___ a lloveer esta tarde.'","context":"Es probable que empiece a llover esta tarde antes de las seis.","options":["A) empiece","B) empieza","C) empezará","D) empezó"],"correct":"A","explanation":"'Es probable que' + epävarmuus → subjunktiivi. 'Empieza' (indikatiivi) on yleinen virhe ilman kielioppitietoisuutta.","rule":"es_probable_que_subj"},
  {"id":2,"type":"gap","question":"Täydennä: 'Aunque ___ difícil, lo conseguiremos.'","context":"Aunque sea difícil, lo conseguiremos con mucho esfuerzo y dedicación.","options":["A) sea","B) es","C) será","D) era"],"correct":"A","explanation":"'Aunque + subjunktiivi' = vaikka(pa) olisi (hypoteesi). 'Aunque es' = vaikka on (tunnustettu fakta). M:llä tämä nyanssi.","rule":"aunque_subjuntivo_hipotesis"},
  {"id":3,"type":"gap","question":"Täydennä: 'Busco un piso que ___ cerca del metro.'","context":"Busco un piso que esté cerca del metro y tenga dos dormitorios.","options":["A) esté","B) está","C) estará","D) estaba"],"correct":"A","explanation":"Tuntematon etsitty asia → subjunktiivi. 'Está' tarkoittaisi että tietty asunto on olemassa.","rule":"relativo_indefinido_subj"},
  {"id":4,"type":"gap","question":"Täydennä: 'Me sorprende que no ___ venido a la reunión.'","context":"Me sorprende que no haya venido a la reunión de esta mañana.","options":["A) haya","B) ha","C) había","D) habrá"],"correct":"A","explanation":"Tunneilmaus + että-lause → subjunktiivin perfekti (haya venido). 'Ha venido' (indikatiivi) on virhe.","rule":"sorprender_que_subj_perf"}
]$json$::jsonb, 1.0),

('grammar', 'M', 'subjunctive', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'No hay nadie que ___ tanto como él.'","context":"No hay nadie que sepa tanto como él sobre el tema de la inteligencia artificial.","options":["A) sepa","B) sabe","C) sabía","D) sabrá"],"correct":"A","explanation":"'No hay nadie que' + subjunktiivi (kieltoilmaus joka kumoaa eksistenssin). Vakiolauserakenne.","rule":"no_hay_nadie_que_subj"},
  {"id":2,"type":"gap","question":"Täydennä: 'Quizás ___ mejor esperar hasta mañana.'","context":"Quizás sea mejor esperar hasta mañana antes de tomar una decisión.","options":["A) sea","B) es","C) será","D) era"],"correct":"A","explanation":"'Quizás + subjunktiivi' (epävarma arvaus). 'Quizás es' käy arkipuhessa mutta subjunktiivi on kirjoitetussa kielessä standardi.","rule":"quizas_subjuntivo"},
  {"id":3,"type":"gap","question":"Täydennä: 'Le pedí que me ___ un favor.'","context":"Le pedí que me hiciera un favor muy importante antes del fin de semana.","options":["A) hiciera","B) hacía","C) hizo","D) hace"],"correct":"A","explanation":"Menneisyyden pyyntö (pedí) + että-lause → subjunktiivin imperfekti (hiciera). 'Hacía/hizo' (indikatiivi) on virhe.","rule":"pedir_que_subj_imperfecto"},
  {"id":4,"type":"gap","question":"Täydennä: 'Por mucho que ___, no lo conseguirás.'","context":"Por mucho que intentes, no lo conseguirás sin la ayuda de un experto.","options":["A) intentes","B) intentas","C) intentaste","D) intentarás"],"correct":"A","explanation":"'Por mucho que + subjunktiivi' = niin paljon kuin (myönnytyslause). Vakiorakenne.","rule":"por_mucho_que_subj"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · M · conditional ───────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'M', 'conditional', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Si tuviera tiempo, ___ a visitarte más a menudo.'","context":"Si tuviera tiempo, iría a visitarte más a menudo a tu casa.","options":["A) iría","B) iba","C) fui","D) voy"],"correct":"A","explanation":"Irreaalinen ehtolause: si + subjunktiivin imperfekti + konditionaali. Iba/fui/voy eivät sovi hypoteettiseen tilanteeseen.","rule":"condicional_irreal_presente"},
  {"id":2,"type":"gap","question":"Täydennä: 'Me dijeron que ___ el paquete hoy.'","context":"Me dijeron que llegaría el paquete hoy por la mañana temprano.","options":["A) llegaría","B) llegaba","C) llegó","D) llega"],"correct":"A","explanation":"Raportoitu tulevaisuus menneisyydessä → konditionaali. Llegaba/llegó ovat imperfekti/preteriti = eri merkitys.","rule":"condicional_discurso_indirecto"},
  {"id":3,"type":"gap","question":"Täydennä: '___ muchas vidas si la reacción hubiera sido más rápida.'","context":"Se habrían salvado muchas vidas si la reacción hubiera sido más rápida.","options":["A) Se habrían salvado","B) Se salvaban","C) Se salvaron","D) Se salvan"],"correct":"A","explanation":"Irreaalinen menneisyyden ehto: si + pluskvamperfektin subjunktiivi → konditionaalin perfekti. M-tason monimutkainen rakenne.","rule":"condicional_perfecto_irreal"},
  {"id":4,"type":"gap","question":"Täydennä: '¿No te ___ lo mismo en su lugar?'","context":"¿No te sentirías de la misma manera si estuvieras en su lugar?","options":["A) sentirías","B) sentías","C) sientes","D) sentiste"],"correct":"A","explanation":"Hypoteettinen kysymys ('jos olisit hänen paikallaan') → konditionaali. Muut aikamuodot eivät sovi hypoteesiin.","rule":"condicional_hipotesis_pregunta"}
]$json$::jsonb, 1.0),

('grammar', 'M', 'conditional', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Yo diría que el presidente ___ equivocado.'","context":"Yo diría que el presidente está equivocado en su análisis de la situación.","options":["A) diría","B) digo","C) decía","D) dije"],"correct":"A","explanation":"'Yo diría que' = lieventelevä mielipide (kohteliaisuus) → konditionaali. 'Yo digo' (indikatiivi) on suorempi mutta töksähtävämpi.","rule":"condicional_opinion_matizada"},
  {"id":2,"type":"gap","question":"Täydennä: 'Serían las diez cuando llegó a casa.'","context":"Serían las diez cuando llegó a casa después del trabajo.","options":["A) Serían","B) Eran","C) Fueron","D) Son"],"correct":"A","explanation":"Kellonajan arvailu menneisyydessä (~klo 10 oli) → konditionaali. 'Eran' = oli varmasti klo 10, 'serían' = luultavasti noin klo 10.","rule":"condicional_conjetura_pasado"},
  {"id":3,"type":"gap","question":"Täydennä: 'Si fuese posible, ___ la fecha de la reunión.'","context":"Si fuese posible, cambiaría la fecha de la reunión al próximo lunes.","options":["A) cambiaría","B) cambiaba","C) cambié","D) cambio"],"correct":"A","explanation":"Irreaalinen nykyhetki → konditionaali. 'Fuese' on subjunktiivin imperfektin vaihtoehtoinen muoto (fuera yleisempi).","rule":"condicional_si_fuese"},
  {"id":4,"type":"gap","question":"Täydennä: '¿Sería tan amable de ___ la puerta?'","context":"¿Sería tan amable de abrir la puerta, por favor? Tengo las manos ocupadas.","options":["A) abrir","B) abra","C) abre","D) abriría"],"correct":"A","explanation":"'Ser tan amable de + infinitiivi' on äärimmäisen kohtelias pyyntö (muodollinen). Muut muodot rikkoisivat kieliopin.","rule":"condicional_ser_amable_de_inf"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · M · preterite_imperfect ───────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'M', 'preterite_imperfect', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: '___ a su madre todos los domingos por la tarde.'","context":"Visitaba a su madre todos los domingos por la tarde antes de que ella enfermara.","options":["A) Visitaba","B) Visitó","C) Ha visitado","D) Visita"],"correct":"A","explanation":"'Todos los domingos' = toistuva tapa → imperfekti. Visitó olisi 'vieraili kerran' (ristiriita 'todos los domingos':n kanssa).","rule":"imperfecto_todos_los"},
  {"id":2,"type":"gap","question":"Täydennä: 'Aquella noche ___ la verdad sobre el asunto.'","context":"Aquella noche supimos la verdad sobre el asunto por primera vez.","options":["A) supimos","B) sabíamos","C) hemos sabido","D) sabemos"],"correct":"A","explanation":"'Saber' preteritissä = saada tietää (muutospiste). 'Sabíamos' = tiesimme (jo olemassa oleva tieto). Verbin merkitys muuttuu!","rule":"saber_preterito_supimos"},
  {"id":3,"type":"gap","question":"Täydennä: 'No ___ que tú también venías a la fiesta.'","context":"No sabía que tú también venías a la fiesta de Marta esta noche.","options":["A) sabía","B) supe","C) he sabido","D) sé"],"correct":"A","explanation":"Taustaehdin (en ollut tietoinen) → imperfekti. 'No supe' olisi 'en saanut tietää' (aktiivinen).","rule":"saber_imperfecto_no_sabia"},
  {"id":4,"type":"gap","question":"Täydennä: 'Cuando ___ la llave, el coche arrancó inmediatamente.'","context":"Cuando giró la llave, el coche arrancó inmediatamente y pudieron salir.","options":["A) giró","B) giraba","C) ha girado","D) gira"],"correct":"A","explanation":"Yksittäinen hetkellinen tapahtuma → preteriti. 'Giraba' kuvaisi 'oli käännössä' (kesto, tausta).","rule":"preterito_hecho_puntual"}
]$json$::jsonb, 1.0),

('grammar', 'M', 'preterite_imperfect', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Mientras ___ la carta, se me cayó la taza.'","context":"Mientras leía la carta, se me cayó la taza de café encima del teclado.","options":["A) leía","B) leí","C) he leído","D) leo"],"correct":"A","explanation":"Mientras + samanaikainen kestävä tausta → imperfekti. 'Leí' katkaisisi kiintolauseen logiikan.","rule":"mientras_imperfecto_accion_simultanea"},
  {"id":2,"type":"gap","question":"Täydennä: 'Una vez ___ el objetivo, celebraron con champán.'","context":"Una vez alcanzaron el objetivo, celebraron con champán en la oficina.","options":["A) alcanzaron","B) alcanzaban","C) han alcanzado","D) alcanzan"],"correct":"A","explanation":"'Una vez + preteriti' = kun kerran (tapahtuma saavutettu). Imperfekti ei sovi saavutettuun tilaan.","rule":"una_vez_preterito"},
  {"id":3,"type":"gap","question":"Täydennä: '___ ser muy temprano cuando sonó el despertador.'","context":"Debía de ser muy temprano cuando sonó el despertador, todavía estaba oscuro.","options":["A) Debía de","B) Debió de","C) Debe","D) Debería"],"correct":"A","explanation":"Arvailu menneisyydessä kestolla (olikohan varhaista) → imperfekti + 'de'. 'Debió de' = päätteli tasan kerran.","rule":"imperfecto_debia_de_conjetura"},
  {"id":4,"type":"gap","question":"Täydennä: 'Tenía una vista impresionante: ___ el mar desde la ventana.'","context":"Tenía una vista impresionante: se veía el mar desde la ventana del salón.","options":["A) se veía","B) se vio","C) se ha visto","D) se ve"],"correct":"A","explanation":"Kuvailu menneisyydessä (taulumainen) → imperfekti. 'Se vio' olisi yksittäinen näkökulma, imperfekti on jatkuva.","rule":"imperfecto_descripcion_visual"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · M · pronouns ──────────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'M', 'pronouns', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'El proyecto ___ estamos trabajando terminará en junio.'","context":"El proyecto en el que estamos trabajando terminará en junio del próximo año.","options":["A) en el que","B) que","C) donde","D) cuyo"],"correct":"A","explanation":"Prepositio (en) + esineviittaus → en el que. Que ilman prepositiota olisi 'el proyecto que termina' (eri merkitys).","rule":"relativo_prep_esine_el_que"},
  {"id":2,"type":"gap","question":"Täydennä: 'Es un autor ___ obras he leído todas.'","context":"Es un autor cuyas obras he leído todas con gran interés.","options":["A) cuyas","B) que","C) quien","D) de quien"],"correct":"A","explanation":"Omistusrelatiivi (hänen teoksensa) → cuyo/a/os/as. Matchaa feminiini-monikko (obras).","rule":"relativo_cuyo_posesivo"},
  {"id":3,"type":"gap","question":"Täydennä: 'No quiero que ___ digas a nadie.'","context":"No quiero que se lo digas a nadie antes de que hable yo con él.","options":["A) se lo","B) le lo","C) le","D) lo"],"correct":"A","explanation":"Le + lo → se lo (pakollinen muunnos). Kaksi pronominia: epäsuora (se ← le) ennen suoraa (lo). M-tasolla hallittava.","rule":"se_lo_obligatorio"},
  {"id":4,"type":"gap","question":"Täydennä: 'Sea lo que ___, no cambiará de opinión.'","context":"Sea lo que sea, no cambiará de opinión sobre este tema polémico.","options":["A) sea","B) es","C) será","D) era"],"correct":"A","explanation":"'Sea lo que sea' = oli mitä oli (kiinteä subjunktiivirakenne). Toistuva verbi samassa muodossa.","rule":"sea_lo_que_sea"}
]$json$::jsonb, 1.0),

('grammar', 'M', 'pronouns', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Los vecinos ___ conocimos el año pasado son muy amables.'","context":"Los vecinos a los que conocimos el año pasado son muy amables y serviciales.","options":["A) a los que","B) que","C) quienes","D) los cuales"],"correct":"A","explanation":"Suora objekti henkilöille + prepositio 'a' → a los que. 'Que' ilman 'a' olisi virhe kun kyseessä henkilöt.","rule":"relativo_a_los_que_personas"},
  {"id":2,"type":"gap","question":"Täydennä: 'Este es el motivo por ___ te llamo.'","context":"Este es el motivo por el que te llamo a estas horas de la noche.","options":["A) el que","B) que","C) lo que","D) cual"],"correct":"A","explanation":"'Por el/la/los/las + que' = jonka takia. 'Motivo' on maskuliini → por el que. 'Por que' ilman artikkelia olisi virhe.","rule":"relativo_por_el_que"},
  {"id":3,"type":"gap","question":"Täydennä: 'Fue entonces cuando me di cuenta de ___.'","context":"Fue entonces cuando me di cuenta de lo que estaba pasando realmente.","options":["A) lo que","B) que","C) lo","D) cual"],"correct":"A","explanation":"'Lo que' = se mikä (neutri relatiivi). 'Que' yksinään vaatisi edeltävän nomini. 'Lo' yksinään ei ole relatiivi.","rule":"relativo_lo_que_neutro"},
  {"id":4,"type":"gap","question":"Täydennä: 'A quien ___ le interese, que levante la mano.'","context":"A quien le interese el tema, que levante la mano para apuntarse al curso.","options":["A) le","B) —","C) la","D) lo"],"correct":"A","explanation":"'A quien le + verbi' = ken(le ikinä), pakollinen 'le' kun 'interesar/gustar'-tyyppiset verbit. 'A quien interese' ilman le olisi virhe.","rule":"a_quien_le_pleonastico"}
]$json$::jsonb, 1.0);
