-- ============================================================
-- Prewarm exercise_bank — E level (eximia cum laude).
-- Vocab: 7 topics × 2 batches = 14 batches / 56 exercises
-- Grammar: 6 topics × 2 batches = 12 batches / 48 exercises
-- Total: 26 batches / 104 exercises.
-- E-level distractors are very close in meaning — differ by register,
-- connotation, or idiomatic usage rather than basic meaning.
-- Schema: matches exercise_bank (migrations/008).
-- ============================================================

-- ─── VOCAB · E · general vocabulary ──────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'E', 'general vocabulary', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Su propuesta resultó sumamente atinada' — mitä tarkoittaa 'atinada'?","context":"Su propuesta resultó sumamente atinada y fue aceptada por unanimidad en la reunión.","options":["A) osuva","B) järkevä","C) oikeudenmukainen","D) ystävällinen"],"correct":"A","explanation":"atinado = osuva, osuvasti muotoiltu (täsmällinen). sensato = järkevä (yleinen), justo = oikeudenmukainen, amable = ystävällinen. E-tasolla nyanssit ratkaisevat."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'nitistää väitteensä' (kumota)?","context":"El profesor refutó todas sus afirmaciones con datos irrefutables.","options":["A) refutar","B) negar","C) rechazar","D) contradecir"],"correct":"A","explanation":"refutar = kumota argumentein (akateeminen). negar = kieltää (peruuttaa), rechazar = hylätä, contradecir = vastustaa sanallisesti. Kirjoitetussa akateemisessa kielessä refutar."},
  {"id":3,"type":"gap","question":"Täydennä: 'Sus palabras ___ un eco profundo en el auditorio.'","context":"Sus palabras suscitaron un eco profundo en el auditorio durante el acto académico.","options":["A) suscitaron","B) hicieron","C) causaron","D) crearon"],"correct":"A","explanation":"suscitar = herättää (tunteita, keskustelua — muodollinen). hacer/causar/crear ovat liian yleisiä akateemisessa tekstissä."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el desempeño'?","context":"El desempeño del equipo ha sido excepcional esta temporada.","options":["A) suoriutuminen","B) esiintyminen","C) voitto","D) yritys"],"correct":"A","explanation":"el desempeño = suoriutuminen (työssä/tehtävässä). la actuación = esiintyminen (taide), la victoria = voitto, el intento = yritys."}
]$json$::jsonb, 1.0),

('vocab', 'E', 'general vocabulary', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Sus argumentos resultaron endebles ante las pruebas presentadas' — mitä tarkoittaa 'endeble'?","context":"Sus argumentos resultaron endebles ante las pruebas contundentes presentadas por la defensa.","options":["A) heikko","B) väärä","C) yksinkertainen","D) vanha"],"correct":"A","explanation":"endeble = heikko, ei-uskottava (argumenteista). falso = väärä, simple = yksinkertainen, antiguo = vanha. E-tasolla 'débil' tavallinen mutta endeble nyansoidumpi."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'hahmottaa' (abstraktisti)?","context":"Cuesta vislumbrar una salida en este momento.","options":["A) vislumbrar","B) ver","C) imaginar","D) entender"],"correct":"A","explanation":"vislumbrar = hahmottaa (vaikeasti näkyvä, metaforinen). ver = nähdä, imaginar = kuvitella, entender = ymmärtää. 'Vislumbrar una salida' on kirjallinen kollokaatio."},
  {"id":3,"type":"gap","question":"Täydennä: 'El incidente ___ un interés mediático inusitado.'","context":"El incidente despertó un interés mediático inusitado durante semanas enteras.","options":["A) despertó","B) creó","C) trajo","D) llevó"],"correct":"A","explanation":"despertar interés = herättää kiinnostusta (kiinteä kollokaatio). crear/traer/llevar eivät luo yhtä voimakasta mielikuvaa."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la índole'?","context":"Se trata de un problema de índole estrictamente personal.","options":["A) luonne (asian)","B) ongelma","C) aihe","D) alue"],"correct":"A","explanation":"la índole = luonne, laatu (asian). el problema = ongelma, el tema = aihe, el área = alue. 'De índole' on muodollinen rakenne."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · E · travel and transport ────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'E', 'travel and transport', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'El turismo masificado deteriora el patrimonio' — mitä tarkoittaa 'masificado'?","context":"El turismo masificado deteriora el patrimonio histórico de las ciudades europeas.","options":["A) massoittunut","B) kansainvälinen","C) kallis","D) järjestetty"],"correct":"A","explanation":"masificado = massoittunut (liikaa ihmisiä). internacional = kansainvälinen, caro = kallis, organizado = järjestetty. Turismoon erikoistunut E-sana."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'vaikutus' (erit. ympäristöön)?","context":"El impacto del turismo en la economía local es innegable.","options":["A) el impacto","B) el efecto","C) la influencia","D) el cambio"],"correct":"A","explanation":"el impacto = vaikutus (voimakas, usein ympäristö/talous). el efecto = vaikutus (neutraali), la influencia = vaikutusvalta, el cambio = muutos."},
  {"id":3,"type":"gap","question":"Täydennä: 'Los viajeros ___ de un servicio impecable durante todo el trayecto.'","context":"Los viajeros disfrutaron de un servicio impecable durante todo el trayecto en tren.","options":["A) disfrutaron de","B) tuvieron","C) recibieron","D) consiguieron"],"correct":"A","explanation":"disfrutar de = nauttia jostakin (kohteliaan/muodollinen rekisteri). tener/recibir/conseguir ovat arkisempiä."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el trayecto'?","context":"El trayecto Madrid–Barcelona en AVE dura dos horas y media.","options":["A) matka (väli)","B) lippu","C) aikataulu","D) pysähdys"],"correct":"A","explanation":"el trayecto = matkaväli, reitti. el billete = lippu, el horario = aikataulu, la parada = pysähdys."}
]$json$::jsonb, 1.0),

('vocab', 'E', 'travel and transport', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'El auge del turismo sostenible es patente' — mitä tarkoittaa 'el auge'?","context":"El auge del turismo sostenible es patente en las cifras del último quinquenio.","options":["A) nousu","B) kiinnostus","C) muutos","D) markkinat"],"correct":"A","explanation":"el auge = nousu (voimakas kasvu). el interés = kiinnostus, el cambio = muutos, el mercado = markkinat. E-tasolla talousjournalistien vakiosana."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'kattaa' (tarpeet)?","context":"Esta oferta cubre todas las necesidades del viajero exigente.","options":["A) cubrir","B) tener","C) ofrecer","D) contener"],"correct":"A","explanation":"cubrir las necesidades = kattaa tarpeet (kollokaatio). tener/ofrecer/contener eivät muodosta yhtä täsmällistä merkitystä."},
  {"id":3,"type":"gap","question":"Täydennä: 'Las aerolíneas ___ tarifas más flexibles tras la pandemia.'","context":"Las aerolíneas han instaurado tarifas más flexibles tras la pandemia para recuperar clientes.","options":["A) han instaurado","B) han puesto","C) han dado","D) han hecho"],"correct":"A","explanation":"instaurar tarifas = ottaa käyttöön hinnasto (virallinen). poner/dar/hacer ovat liian arkisia liiketoiminnassa."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la pernoctación'?","context":"El precio incluye dos pernoctaciones en hotel de cuatro estrellas.","options":["A) yöpyminen","B) ateria","C) matka","D) vierailu"],"correct":"A","explanation":"la pernoctación = yöpyminen (virallinen matkailuterminologia). la comida = ateria, el viaje = matka, la visita = vierailu."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · E · health and body ─────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'E', 'health and body', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Hay que paliar los efectos del insomnio crónico' — mitä tarkoittaa 'paliar'?","context":"Hay que paliar los efectos del insomnio crónico mediante técnicas de relajación.","options":["A) lieventää","B) parantaa","C) ehkäistä","D) analysoida"],"correct":"A","explanation":"paliar = lieventää (oireita, ei paranna). curar = parantaa (täysin), prevenir = ehkäistä, analizar = analysoida. Lääketieteellisessä kielessä paliar."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'parantumaton' (sairaus)?","context":"Se trata de una enfermedad incurable pero se puede controlar.","options":["A) incurable","B) grave","C) crónico","D) permanente"],"correct":"A","explanation":"incurable = parantumaton. grave = vakava, crónico = krooninen (pitkäaikainen mutta voi parantua), permanente = pysyvä. Niiden väliset nyanssit E-tasolla."},
  {"id":3,"type":"gap","question":"Täydennä: 'Los hábitos saludables ___ una vida más plena.'","context":"Los hábitos saludables propician una vida más plena y satisfactoria.","options":["A) propician","B) hacen","C) dan","D) traen"],"correct":"A","explanation":"propiciar = edistää, suosia (saada aikaan suotuisia olosuhteita). hacer/dar/traer eivät vastaa sävyä."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el desgaste'?","context":"El desgaste físico tras la competición fue considerable.","options":["A) kuluminen","B) väsymys","C) loukkaantuminen","D) kipu"],"correct":"A","explanation":"el desgaste = kuluminen (fyysinen/henkinen kuormitus). el cansancio = väsymys (lievempi), la lesión = loukkaantuminen, el dolor = kipu."}
]$json$::jsonb, 1.0),

('vocab', 'E', 'health and body', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Los tratamientos paliativos mejoran la calidad de vida' — mitä tarkoittaa 'paliativo'?","context":"Los tratamientos paliativos mejoran la calidad de vida de los pacientes terminales.","options":["A) oireita lievittävä","B) parantava","C) ennaltaehkäisevä","D) kuntouttava"],"correct":"A","explanation":"paliativo = oireita lievittävä (ei paranna). curativo = parantava, preventivo = ennaltaehkäisevä, rehabilitador = kuntouttava."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'väsymys' (pitkäaikainen, voimakas)?","context":"Sufría un agotamiento extremo por el exceso de trabajo.","options":["A) el agotamiento","B) el cansancio","C) la fatiga","D) el sueño"],"correct":"A","explanation":"el agotamiento = uupumus (äärimmäinen). el cansancio = väsymys (normaali), la fatiga = fatiikki (lääketiet.), el sueño = unisuus."},
  {"id":3,"type":"gap","question":"Täydennä: 'La medicina preventiva ___ muchas patologías.'","context":"La medicina preventiva evita muchas patologías graves en fases tempranas.","options":["A) evita","B) quita","C) rompe","D) pierde"],"correct":"A","explanation":"evitar patologías = välttää sairaudet (muodollinen). quitar/romper/perder eivät sovi sairauskontekstiin."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la afección'?","context":"Presenta una afección cardíaca que requiere seguimiento constante.","options":["A) vaiva","B) tunne","C) rakkaus","D) vaikutus"],"correct":"A","explanation":"la afección = vaiva, sairaus (lääket.). VAROITUS: 'afecto' = kiintymys, 'afectar' = vaikuttaa — false friend -vaara E-tasolla."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · E · society and politics ────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'E', 'society and politics', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La ciudadanía exige transparencia' — mitä tarkoittaa 'la ciudadanía'?","context":"La ciudadanía exige transparencia total en la gestión de los fondos públicos.","options":["A) kansalaisyhteiskunta","B) kaupunki","C) yhteisö","D) julkisuus"],"correct":"A","explanation":"la ciudadanía = kansalaisyhteiskunta, kansalaiset kollektiivina. la ciudad = kaupunki, la comunidad = yhteisö, la publicidad = julkisuus/mainonta."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'vaarantaa' (vakava)?","context":"Esas decisiones podrían vulnerar derechos fundamentales.","options":["A) vulnerar","B) romper","C) herir","D) dañar"],"correct":"A","explanation":"vulnerar derechos = loukata/vaarantaa oikeuksia (juridinen). romper = rikkoa (konkreettinen), herir = haavoittaa, dañar = vahingoittaa. Juridisessa rekisterissä vulnerar."},
  {"id":3,"type":"gap","question":"Täydennä: 'El debate ___ la necesidad de una reforma estructural.'","context":"El debate puso de manifiesto la necesidad de una reforma estructural profunda.","options":["A) puso de manifiesto","B) mostró","C) enseñó","D) dijo"],"correct":"A","explanation":"poner de manifiesto = tuoda esiin, paljastaa (muodollinen ilmaus). mostrar/enseñar/decir eivät vastaa sävyä."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el hito'?","context":"Las elecciones marcaron un hito en la historia democrática del país.","options":["A) virstanpylväs","B) päivä","C) vaalit","D) muutos"],"correct":"A","explanation":"el hito = virstanpylväs (historiallinen merkkipaalu). el día = päivä, las elecciones = vaalit, el cambio = muutos."}
]$json$::jsonb, 1.0),

('vocab', 'E', 'society and politics', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'El gobierno se ha visto instado a dimitir' — mitä tarkoittaa 'instar'?","context":"El gobierno se ha visto instado a dimitir tras el escándalo de corrupción.","options":["A) kehottaa painokkaasti","B) pyytää","C) auttaa","D) puolustaa"],"correct":"A","explanation":"instar = kehottaa painokkaasti (muodollinen, usein vaatia). pedir = pyytää (lievempi), ayudar = auttaa, defender = puolustaa."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'epäkohta' (yhteiskunnallinen)?","context":"Hay que denunciar las injusticias que afectan a los colectivos vulnerables.","options":["A) la injusticia","B) el problema","C) la diferencia","D) la dificultad"],"correct":"A","explanation":"la injusticia = epäoikeudenmukaisuus, epäkohta. el problema = ongelma (yleinen), la diferencia = ero, la dificultad = vaikeus."},
  {"id":3,"type":"gap","question":"Täydennä: 'La nueva ley ___ los derechos de los trabajadores migrantes.'","context":"La nueva ley salvaguarda los derechos de los trabajadores migrantes en situación vulnerable.","options":["A) salvaguarda","B) guarda","C) cuida","D) protege"],"correct":"A","explanation":"salvaguardar = varjella (virallinen, juridinen). guardar = säilyttää (konkreettinen), cuidar = hoitaa, proteger = suojella (neutraali). Juridisessa kielessä salvaguardar."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la injerencia'?","context":"El informe denuncia la injerencia extranjera en las elecciones.","options":["A) puuttuminen","B) tutkimus","C) neuvottelu","D) tuki"],"correct":"A","explanation":"la injerencia = puuttuminen (ei-toivottu). la investigación = tutkimus, la negociación = neuvottelu, el apoyo = tuki."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · E · environment and nature ──────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'E', 'environment and nature', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Los ecosistemas marinos se ven mermados por la sobrepesca' — mitä tarkoittaa 'mermar'?","context":"Los ecosistemas marinos se ven mermados drásticamente por la sobrepesca industrial.","options":["A) vähentää","B) tuhota","C) muuttaa","D) rikkoa"],"correct":"A","explanation":"mermar = vähentää (asteittain). destruir = tuhota (täysin), cambiar = muuttaa, romper = rikkoa. E-tasolla 'mermar' viittaa resurssien vähenemiseen."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'hupeneva' (resurssit)?","context":"Los recursos menguantes nos obligan a cambiar de modelo.","options":["A) menguante","B) poco","C) pequeño","D) escaso"],"correct":"A","explanation":"menguante = hupeneva (dynaaminen, aktiivisesti vähenevä). poco = vähän, pequeño = pieni, escaso = niukka (staattinen tila)."},
  {"id":3,"type":"gap","question":"Täydennä: 'La biodiversidad ___ un declive preocupante.'","context":"La biodiversidad experimenta un declive preocupante desde hace décadas.","options":["A) experimenta","B) hace","C) tiene","D) ve"],"correct":"A","explanation":"experimentar un declive = kokea lasku (muodollinen, tieteellinen). hacer/tener/ver ovat liian arkisia biologian diskurssissa."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la sobreexplotación'?","context":"La sobreexplotación de los acuíferos pone en riesgo el suministro de agua.","options":["A) ylikuormitus","B) käyttö","C) hyödyntäminen","D) tuhlaus"],"correct":"A","explanation":"la sobreexplotación = liikakäyttö, ylikuormitus. el uso = käyttö (neutraali), el aprovechamiento = hyödyntäminen, el despilfarro = tuhlaus."}
]$json$::jsonb, 1.0),

('vocab', 'E', 'environment and nature', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Hay que atajar la deforestación con medidas urgentes' — mitä tarkoittaa 'atajar'?","context":"Hay que atajar la deforestación con medidas urgentes y coordinadas a nivel global.","options":["A) pysäyttää","B) hidastaa","C) tutkia","D) estää"],"correct":"A","explanation":"atajar = pysäyttää, leikata poikki (ongelma). ralentizar = hidastaa, investigar = tutkia, impedir = estää (ennakolta)."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'järkyttää' (tasapainoa)?","context":"El cambio climático perturba los ecosistemas más frágiles.","options":["A) perturbar","B) cambiar","C) mover","D) afectar"],"correct":"A","explanation":"perturbar = järkyttää (tasapainoa). cambiar = muuttaa, mover = liikuttaa, afectar = vaikuttaa (neutraali). Tieteellisessä kielessä perturbar."},
  {"id":3,"type":"gap","question":"Täydennä: 'Las políticas medioambientales ___ una revisión profunda.'","context":"Las políticas medioambientales requieren una revisión profunda y urgente.","options":["A) requieren","B) quieren","C) piden","D) buscan"],"correct":"A","explanation":"requerir = vaatia (muodollinen, asioista). querer/pedir/buscar ovat aktiivisia tekijöitä — eivät sovi abstrakteille politiikoille E-tasolla."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la merma'?","context":"La merma de especies autóctonas es un problema ecológico grave.","options":["A) väheneminen","B) kasvu","C) muutos","D) siirtyminen"],"correct":"A","explanation":"la merma = väheneminen (aktiivinen menetys). el crecimiento = kasvu (vastakohta), el cambio = muutos, la migración = siirtyminen."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · E · culture and arts ────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'E', 'culture and arts', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La obra rezuma originalidad en cada página' — mitä tarkoittaa 'rezumar'?","context":"La obra rezuma originalidad en cada página y sorprende al lector constantemente.","options":["A) huokua","B) näyttää","C) sisältää","D) olla"],"correct":"A","explanation":"rezumar = huokua, tihkua (luonne ulospäin). mostrar = näyttää (aktiivinen), contener = sisältää, ser = olla. 'Rezumar' on kirjallinen metafora."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'lumoava' (taideteos)?","context":"Es una obra cautivadora que atrapa desde la primera escena.","options":["A) cautivador","B) interesante","C) bonito","D) emocionante"],"correct":"A","explanation":"cautivador = lumoava (intensiivinen). interesante = mielenkiintoinen (neutraali), bonito = kaunis, emocionante = tunteisiin vetoava."},
  {"id":3,"type":"gap","question":"Täydennä: 'El escritor ___ un universo literario propio.'","context":"El escritor ha forjado un universo literario propio a lo largo de décadas.","options":["A) ha forjado","B) ha hecho","C) ha creado","D) ha escrito"],"correct":"A","explanation":"forjar un universo = takoa, luoda ajan kanssa (voimakas metafora). hacer/crear/escribir ovat neutraaleja — forjar kantaa taiteellista painoa."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la trama'?","context":"La trama de la novela es intrincada pero absolutamente coherente.","options":["A) juoni","B) hahmot","C) tunnelma","D) tyyli"],"correct":"A","explanation":"la trama = juoni (kirjallinen). los personajes = hahmot, la atmósfera = tunnelma, el estilo = tyyli."}
]$json$::jsonb, 1.0),

('vocab', 'E', 'culture and arts', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Su obra tardía se caracteriza por un marcado pesimismo' — mitä tarkoittaa 'tardío'?","context":"Su obra tardía se caracteriza por un marcado pesimismo y una introspección profunda.","options":["A) myöhäinen (tuotantokausi)","B) viimeinen","C) hidas","D) myöhästynyt"],"correct":"A","explanation":"tardío = myöhäinen (uratason kausi). último = viimeinen (kronologisesti), lento = hidas, retrasado = myöhästynyt. Taidehistorian 'obra tardía' on vakiintunut termi."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'päättää' (taiteellisesti muotoilla)?","context":"El artista plasmó sus ideas en una serie de esculturas monumentales.","options":["A) plasmar","B) hacer","C) mostrar","D) explicar"],"correct":"A","explanation":"plasmar = ilmentää, muotoilla konkreettiseksi. hacer = tehdä (yleinen), mostrar = näyttää, explicar = selittää. 'Plasmar ideas' on taidekollokaatio."},
  {"id":3,"type":"gap","question":"Täydennä: 'La película ___ una reflexión aguda sobre la identidad.'","context":"La película ofrece una reflexión aguda sobre la identidad cultural contemporánea.","options":["A) ofrece","B) da","C) hace","D) tiene"],"correct":"A","explanation":"ofrecer una reflexión = tarjota pohdinta (kriittinen kollokaatio). dar/hacer/tener eivät sovi kriitikkokieleen."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el legado'?","context":"El legado cultural de esta generación sigue vivo tres décadas después.","options":["A) perintö","B) teos","C) tyyli","D) muisto"],"correct":"A","explanation":"el legado = perintö (kulttuurinen). la obra = teos, el estilo = tyyli, el recuerdo = muisto."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · E · work and economy ────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'E', 'work and economy', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La empresa acusa una caída notable de ingresos' — mitä tarkoittaa 'acusar'?","context":"La empresa acusa una caída notable de ingresos en el último trimestre fiscal.","options":["A) osoittaa (kokea)","B) syyttää","C) kieltää","D) pelätä"],"correct":"A","explanation":"acusar (talouskieli) = osoittaa, kokea (esim. laskua). VAROITUS: yleensä 'acusar' = syyttää — rekisteri muuttaa merkityksen. E-tasolla tämä nyanssi."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'kasvattaa' (pääomaa)?","context":"La firma incrementó su capital un quince por ciento.","options":["A) incrementar","B) subir","C) crecer","D) aumentar"],"correct":"A","explanation":"incrementar = kasvattaa (virallinen, yritysviestintä). subir = nousta (arki), crecer = kasvaa (intransitiivinen), aumentar = lisätä (yleisempi). Raporteissa incrementar."},
  {"id":3,"type":"gap","question":"Täydennä: 'El mercado laboral ___ signos de recuperación.'","context":"El mercado laboral muestra signos claros de recuperación tras la crisis.","options":["A) muestra","B) da","C) tiene","D) hace"],"correct":"A","explanation":"mostrar signos = näyttää merkkejä (talouskollokaatio). dar/tener/hacer signos eivät ole standardeja taloustekstissä."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la desaceleración'?","context":"La desaceleración económica preocupa a los analistas financieros.","options":["A) kasvun hidastuminen","B) lama","C) kriisi","D) muutos"],"correct":"A","explanation":"la desaceleración = (kasvun) hidastuminen. la recesión = lama, la crisis = kriisi, el cambio = muutos. Hieno nyanssi E-tasolla."}
]$json$::jsonb, 1.0),

('vocab', 'E', 'work and economy', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Las empresas multinacionales eluden el pago de impuestos' — mitä tarkoittaa 'eludir'?","context":"Las empresas multinacionales eluden el pago de impuestos mediante paraísos fiscales.","options":["A) kiertää (laillisesti)","B) vältellä","C) kieltäytyä","D) lopettaa"],"correct":"A","explanation":"eludir impuestos = kiertää veroja (lain puitteissa; eri kuin 'evadir' joka on rikos). evitar = välttää, rehusar = kieltäytyä, parar = lopettaa."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'palkkaero'?","context":"La brecha salarial entre géneros persiste pese a las leyes vigentes.","options":["A) la brecha salarial","B) la diferencia","C) el problema","D) el conflicto"],"correct":"A","explanation":"la brecha salarial = palkkakuilu (vakiintunut termi). la diferencia = ero (neutraali), el problema = ongelma, el conflicto = konflikti."},
  {"id":3,"type":"gap","question":"Täydennä: 'El sector tecnológico ___ un crecimiento exponencial.'","context":"El sector tecnológico registra un crecimiento exponencial en los últimos años.","options":["A) registra","B) tiene","C) ve","D) hace"],"correct":"A","explanation":"registrar crecimiento = kirjata kasvu (tilastollinen, muodollinen). tener/ver/hacer ovat arkisempia."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la coyuntura'?","context":"La coyuntura económica actual exige cautela en las inversiones.","options":["A) suhdanne","B) markkinat","C) talous","D) tilanne"],"correct":"A","explanation":"la coyuntura = suhdanne, taloudellinen tilannekuva. el mercado = markkinat, la economía = talous, la situación = tilanne (liian yleinen)."}
]$json$::jsonb, 1.0);

-- ============================================================
-- GRAMMAR · E · 6 topics × 2 batches = 12 batches / 48 exercises
-- ============================================================

-- ─── GRAMMAR · E · ser_estar ─────────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'E', 'ser_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'El examen al que te presentas ___ de una exigencia considerable.'","context":"El examen al que te presentas es de una exigencia considerable, requiere preparación seria.","options":["A) es","B) está","C) hay","D) tiene"],"correct":"A","explanation":"Kokeen ominaisuus (vaativuus on piirre) → ser de + ominaisuus. 'Está de' olisi kiinteä ilmaus eri merkityksellä (estar de viaje).","rule":"ser_de_caracteristica"},
  {"id":2,"type":"gap","question":"Täydennä: 'Los resultados ___ muy por debajo de lo esperado.'","context":"Los resultados del trimestre están muy por debajo de lo esperado por el consejo.","options":["A) están","B) son","C) hay","D) tienen"],"correct":"A","explanation":"Tulosten sijainti skaalalla (tilapäinen arvio) → estar. 'Son por debajo' olisi kielioppivirhe — 'estar por debajo/encima' on vakiintunut paikkailmaus.","rule":"estar_por_debajo"},
  {"id":3,"type":"gap","question":"Täydennä: 'La decisión ___ tomada antes del próximo lunes.'","context":"La decisión deberá ser tomada antes del próximo lunes por la dirección.","options":["A) ser","B) estar","C) haber","D) tener"],"correct":"A","explanation":"Tekopassiivi tulevaisuudessa → ser + partisiippi ('deberá ser tomada' = on tehtävä). 'Estar tomada' ilmaisisi lopputulosta, ei toimintaa.","rule":"ser_pasiva_accion"},
  {"id":4,"type":"gap","question":"Täydennä: 'La ciudad ___ más tranquila que nunca aquella noche.'","context":"La ciudad estaba más tranquila que nunca aquella noche de niebla intensa.","options":["A) estaba","B) era","C) fue","D) hubo"],"correct":"A","explanation":"Kaupungin tilapäinen tila sinä yönä → estar. 'Era tranquila' = oli rauhallinen luonteeltaan (pysyvä piirre).","rule":"estar_tilapainen_aikamuoto"}
]$json$::jsonb, 1.0),

('grammar', 'E', 'ser_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'La propuesta ___ sobre la mesa desde hace semanas.'","context":"La propuesta está sobre la mesa desde hace semanas sin que nadie la haya comentado.","options":["A) está","B) es","C) hay","D) tiene"],"correct":"A","explanation":"'Estar sobre la mesa' = olla pöydällä (kuvaannollinen: neuvottelujen käynnissä). 'Ser sobre la mesa' olisi virhe.","rule":"estar_sobre_la_mesa"},
  {"id":2,"type":"gap","question":"Täydennä: 'Lo más interesante de su teoría ___ la conclusión final.'","context":"Lo más interesante de su teoría es la conclusión final, muy provocadora.","options":["A) es","B) está","C) hay","D) tiene"],"correct":"A","explanation":"'Lo + superlatiivi + ser' = tärkein/parasta on. Abstrakti identifikaatio → ser. 'Está' olisi paikka, mikä ei sovi.","rule":"lo_mas_es"},
  {"id":3,"type":"gap","question":"Täydennä: 'El ministro ___ convencido de que la reforma saldrá adelante.'","context":"El ministro está convencido de que la reforma saldrá adelante pese a las críticas.","options":["A) está","B) es","C) hay","D) tiene"],"correct":"A","explanation":"'Estar convencido' = olla vakuuttunut (mielentila). 'Ser convencido' olisi passiivi ('häntä vakuutettiin'), eri merkitys.","rule":"estar_convencido"},
  {"id":4,"type":"gap","question":"Täydennä: 'Ese comportamiento ___ digno de elogio.'","context":"Ese comportamiento durante la crisis es digno de elogio y debe reconocerse.","options":["A) es","B) está","C) hay","D) tiene"],"correct":"A","explanation":"'Ser digno de' = olla ansaitseva (arvoarvio, pysyvä). Vakiintunut ser-kollokaatio.","rule":"ser_digno_de"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · E · hay_estar ─────────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'E', 'hay_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'No ___ cabida para el error en este proyecto.'","context":"No hay cabida para el error en este proyecto de alta precisión técnica.","options":["A) hay","B) está","C) es","D) tiene"],"correct":"A","explanation":"'No hay cabida' = ei ole tilaa (kiinteä muodollinen ilmaus). 'No está cabida' on kielioppivirhe.","rule":"no_hay_cabida"},
  {"id":2,"type":"gap","question":"Täydennä: 'El dossier ___ a disposición de quien lo solicite.'","context":"El dossier está a disposición de quien lo solicite en la secretaría.","options":["A) está","B) hay","C) es","D) tiene"],"correct":"A","explanation":"'Estar a disposición' = olla käytettävissä (kiinteä muodollinen ilmaus). 'Hay a disposición' ei ole kieliopillinen.","rule":"estar_a_disposicion"},
  {"id":3,"type":"gap","question":"Täydennä: '___ quien defienda esa postura, pero son minoría.'","context":"Hay quien defienda esa postura, pero son minoría en el debate público.","options":["A) Hay","B) Están","C) Son","D) Existe"],"correct":"A","explanation":"'Hay quien + subjunktiivi' = on niitä jotka (epämäärä henkilö). Rakenne vaatii hay:ta, ei muita verbejä.","rule":"hay_quien_subj"},
  {"id":4,"type":"gap","question":"Täydennä: 'El informe ___ pendiente de aprobación.'","context":"El informe está pendiente de aprobación por parte del comité ejecutivo.","options":["A) está","B) es","C) hay","D) tiene"],"correct":"A","explanation":"'Estar pendiente de' = olla odottamassa (hyväksyntää). Tila, ei olemassaolo → estar.","rule":"estar_pendiente_de"}
]$json$::jsonb, 1.0),

('grammar', 'E', 'hay_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: '___ de por medio una serie de obstáculos.'","context":"Hay de por medio una serie de obstáculos que complican la negociación.","options":["A) Hay","B) Está","C) Es","D) Son"],"correct":"A","explanation":"'Hay de por medio' = (jotain) esteenä, asian välissä. Kiinteä idiomaattinen rakenne hay-verbin kanssa.","rule":"hay_de_por_medio"},
  {"id":2,"type":"gap","question":"Täydennä: 'El acuerdo ___ en vigor desde el pasado enero.'","context":"El acuerdo está en vigor desde el pasado enero tras años de negociación.","options":["A) está","B) es","C) hay","D) tiene"],"correct":"A","explanation":"'Estar en vigor' = olla voimassa (kiinteä juridinen ilmaus). 'Ser en vigor' olisi kielioppivirhe.","rule":"estar_en_vigor"},
  {"id":3,"type":"gap","question":"Täydennä: 'No ___ lugar a dudas sobre su culpabilidad.'","context":"No hay lugar a dudas sobre su culpabilidad tras las pruebas presentadas.","options":["A) hay","B) está","C) es","D) tiene"],"correct":"A","explanation":"'No hay lugar a dudas' = ei ole epäilyksen sijaa (vakiintunut muodollinen ilmaus). Aina hay, ei estar.","rule":"no_hay_lugar_a_dudas"},
  {"id":4,"type":"gap","question":"Täydennä: 'La reunión ___ prevista para las cuatro de la tarde.'","context":"La reunión está prevista para las cuatro de la tarde en la sala principal.","options":["A) está","B) es","C) hay","D) tiene"],"correct":"A","explanation":"'Estar previsto/a' = olla suunniteltu. Partisiippi tilan ilmaisijana → estar. Huom: 'la reunión es a las cuatro' (tapahtuman aika → ser), mutta 'está prevista' → estar.","rule":"estar_previsto_vs_ser_evento"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · E · subjunctive ───────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'E', 'subjunctive', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Por más que ___, no cambiará de opinión.'","context":"Por más que le insistas, no cambiará de opinión sobre este asunto tan delicado.","options":["A) le insistas","B) le insistes","C) le insististe","D) le insistirás"],"correct":"A","explanation":"'Por más que + subjunktiivi' = niin paljon kuin. Myönnytyslause, vakiorakenne subjunktiivilla.","rule":"por_mas_que_subj"},
  {"id":2,"type":"gap","question":"Täydennä: 'Ojalá ___ tenido más tiempo para prepararme.'","context":"Ojalá hubiera tenido más tiempo para prepararme antes del examen final.","options":["A) hubiera","B) había","C) habría","D) tenía"],"correct":"A","explanation":"'Ojalá + pluskvamperfektin subjunktiivi' = kunpa olisin (menneisyyden mahdottomuus). Habría (konditionaalin perfekti) on yleinen virhe.","rule":"ojala_hubiera_irreal_pasado"},
  {"id":3,"type":"gap","question":"Täydennä: 'Antes de que ___ una decisión, consideremos todas las opciones.'","context":"Antes de que tomemos una decisión definitiva, consideremos todas las opciones disponibles.","options":["A) tomemos","B) tomamos","C) tomaremos","D) tomábamos"],"correct":"A","explanation":"'Antes de que + subjunktiivi' aina (vaikka subjekti olisi sama — 'antes de tomar' ilman que käy). Tässä subjekti vaihtuu → que + subjunktiivi.","rule":"antes_de_que_subj"},
  {"id":4,"type":"gap","question":"Täydennä: 'Me molesta que ___ así conmigo.'","context":"Me molesta que hables así conmigo delante de otras personas.","options":["A) hables","B) hablas","C) hablarás","D) hablabas"],"correct":"A","explanation":"'Me molesta que + subjunktiivi' (tunneilmaus + toinen subjekti). 'Me molesta que hablas' on yleinen indikatiivi-virhe.","rule":"me_molesta_que_subj"}
]$json$::jsonb, 1.0),

('grammar', 'E', 'subjunctive', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Si ___ la ocasión, no dudaría en aceptar.'","context":"Si se presentara la ocasión, no dudaría en aceptar esa oferta laboral.","options":["A) se presentara","B) se presenta","C) se ha presentado","D) se presentaría"],"correct":"A","explanation":"Irreaalinen ehtolause nykyhetkestä: 'si + subjunktiivin imperfekti → konditionaali'. Presenta (indikatiivi) muuttaisi lauseen reaaliseksi.","rule":"si_subj_imp_condicional"},
  {"id":2,"type":"gap","question":"Täydennä: 'No es que no ___ venir, es que no puedo.'","context":"No es que no quiera venir a la reunión, es que no puedo por motivos personales.","options":["A) quiera","B) quiero","C) quería","D) querré"],"correct":"A","explanation":"'No es que + subjunktiivi' = ei ole niin että (kielto, subjunktiivi pakollinen). 'No es que no quiero' on klassinen virhe.","rule":"no_es_que_subj"},
  {"id":3,"type":"gap","question":"Täydennä: 'Cuesta creer que ___ sucedido algo así.'","context":"Cuesta creer que haya sucedido algo así en una ciudad tan tranquila.","options":["A) haya","B) ha","C) hubiera","D) habrá"],"correct":"A","explanation":"'Cuesta creer que' (vaikeasti uskottava) → subjunktiivin perfekti (haya + partisiippi). Epäily laukaisee subjunktiivin.","rule":"costar_creer_que_subj"},
  {"id":4,"type":"gap","question":"Täydennä: 'Tal vez ___ un error en los datos.'","context":"Tal vez haya un error en los datos que han presentado esta mañana.","options":["A) haya","B) hay","C) ha habido","D) habrá"],"correct":"A","explanation":"'Tal vez + subjunktiivi' (epävarmuus). 'Tal vez hay' käy arkipuheessa mutta subjunktiivi on kirjoitetun kielen standardi.","rule":"tal_vez_subj"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · E · conditional ───────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'E', 'conditional', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Nadie ___ imaginado un desenlace como este.'","context":"Nadie habría imaginado un desenlace como este al comienzo de la historia.","options":["A) habría","B) ha","C) había","D) habrá"],"correct":"A","explanation":"Irreaalinen menneisyys (ei kukaan olisi voinut kuvitella) → konditionaalin perfekti. 'Había' on indikatiivi (pluskvamperfekti).","rule":"condicional_compuesto_irreal"},
  {"id":2,"type":"gap","question":"Täydennä: 'De haberlo sabido, ___ de otra manera.'","context":"De haberlo sabido, habría actuado de otra manera desde el principio.","options":["A) habría actuado","B) actuaría","C) actuaba","D) actué"],"correct":"A","explanation":"'De haber + partisiippi' = jos olisi tiennyt → konditionaalin perfekti seurauksessa. Yksinkertainen konditionaali ei riitä menneisyyden irreaalisuuteen.","rule":"de_haber_condicional_perfecto"},
  {"id":3,"type":"gap","question":"Täydennä: 'La empresa ___ mejor si apostara por la innovación.'","context":"La empresa iría mejor si apostara por la innovación tecnológica en lugar del ahorro.","options":["A) iría","B) iba","C) va","D) fuera"],"correct":"A","explanation":"Si + subjunktiivin imperfekti (apostara) → konditionaali (iría). Klassinen irreaali nykyhetkestä.","rule":"si_subj_imp_condicional_e"},
  {"id":4,"type":"gap","question":"Täydennä: 'Eso ___ pasado solo en una novela.'","context":"Eso solo habría pasado en una novela, no en la realidad cotidiana.","options":["A) habría","B) ha","C) hubiera","D) había"],"correct":"A","explanation":"Mahdottoman menneisyyden kommentointi ('olisi tapahtunut vain...') → konditionaalin perfekti. 'Hubiera pasado' (subjunktiivi) toimisi myös mutta sävy eri.","rule":"habria_pasado_solo_irreal"}
]$json$::jsonb, 1.0),

('grammar', 'E', 'conditional', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Desearía que todo ___ mejor.'","context":"Desearía que todo fuera mejor en la situación política actual del país.","options":["A) fuera","B) es","C) sería","D) era"],"correct":"A","explanation":"'Desearía que + subjunktiivin imperfekti' (toive, joka tuskin toteutuu). Konditionaali tässä paikassa olisi virhe (subjunktiivi pakollinen kontitionaalin toivomuksen jälkeen).","rule":"desearia_que_subj_imp"},
  {"id":2,"type":"gap","question":"Täydennä: 'Convendría ___ las conclusiones con cautela.'","context":"Convendría interpretar las conclusiones con cautela hasta que se confirmen los datos.","options":["A) interpretar","B) interprete","C) interpretara","D) interpretó"],"correct":"A","explanation":"'Convendría + infinitiivi' ilman subjektivaihdosta → infinitiivi. Jos subjekti vaihtuisi ('convendría que interpretara') → subjunktiivi.","rule":"convendria_infinitivo"},
  {"id":3,"type":"gap","question":"Täydennä: 'Me ___ que todos estuvieran de acuerdo.'","context":"Me encantaría que todos estuvieran de acuerdo antes de firmar el documento.","options":["A) encantaría","B) encantaba","C) encanta","D) encantó"],"correct":"A","explanation":"Epärealistinen toive → konditionaali (me encantaría). 'Me encanta' on reaalinen nautinto, 'me encantó' menneisyyden tapahtuma.","rule":"me_encantaria_que"},
  {"id":4,"type":"gap","question":"Täydennä: 'Habida cuenta de los datos, ___ un cambio de rumbo.'","context":"Habida cuenta de los datos, sería oportuno un cambio de rumbo inmediato.","options":["A) sería","B) es","C) será","D) era"],"correct":"A","explanation":"Muodollinen ehdottaminen → konditionaali 'sería oportuno'. 'Habida cuenta de' on E-tason muodollinen aloitus.","rule":"seria_oportuno_formal"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · E · preterite_imperfect ───────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'E', 'preterite_imperfect', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Apenas ___ la noticia, llamó por teléfono.'","context":"Apenas supo la noticia, llamó por teléfono a todos sus familiares.","options":["A) supo","B) sabía","C) ha sabido","D) sabe"],"correct":"A","explanation":"'Apenas + preteriti' = heti kun sai tietää. Saber preteritissä = saada selville (muutospiste).","rule":"apenas_supo_preterito"},
  {"id":2,"type":"gap","question":"Täydennä: 'Aunque ___ todo lo posible, no conseguimos el contrato.'","context":"Aunque hicimos todo lo posible, no conseguimos el contrato con aquella empresa.","options":["A) hicimos","B) hacíamos","C) hemos hecho","D) hacemos"],"correct":"A","explanation":"Päättynyt yritys menneisyydessä → preteriti. 'Hacíamos' olisi 'teimme aikaisemmin yleensä' (toistuva tausta).","rule":"aunque_hicimos_preterito"},
  {"id":3,"type":"gap","question":"Täydennä: 'No ___ intención de ofenderte.'","context":"No tenía intención de ofenderte cuando dije aquello en la reunión.","options":["A) tenía","B) tuve","C) he tenido","D) tengo"],"correct":"A","explanation":"Menneisyyden tausta-asenne → imperfekti. 'No tuve intención' olisi hetkellinen päätös (päättyi), mikä kuulostaa oudolta tässä kontekstissa.","rule":"no_tenia_intencion"},
  {"id":4,"type":"gap","question":"Täydennä: 'Nada más ___ a la oficina, me di cuenta de que faltaba algo.'","context":"Nada más llegar a la oficina, me di cuenta de que faltaba algo importante.","options":["A) llegar","B) llegué","C) llegaba","D) llegando"],"correct":"A","explanation":"'Nada más + infinitiivi' = heti kun saapui. 'Nada más llegué' ei ole kieliopillinen — rakenne vaatii infinitiivin.","rule":"nada_mas_infinitivo"}
]$json$::jsonb, 1.0),

('grammar', 'E', 'preterite_imperfect', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Mientras ___ las obras, la plaza estuvo cerrada.'","context":"Mientras duraban las obras, la plaza estuvo cerrada al tráfico durante meses.","options":["A) duraban","B) duraron","C) han durado","D) duran"],"correct":"A","explanation":"Mientras + jatkuva rinnakkaistausta → imperfekti (duraban). Sen rinnalla preteriti (estuvo cerrada) ilmaisee rajattua kokonaistilaa.","rule":"mientras_duraban_tausta"},
  {"id":2,"type":"gap","question":"Täydennä: 'En cuanto ___ la carta, comprendí todo.'","context":"En cuanto leí la carta, comprendí todo lo que había sucedido aquellos meses.","options":["A) leí","B) leía","C) he leído","D) leo"],"correct":"A","explanation":"'En cuanto + preteriti' = heti kun luin (hetkellinen muutos). 'Leía' olisi jatkuva tausta — ei sovi 'en cuanto':n kanssa.","rule":"en_cuanto_preterito"},
  {"id":3,"type":"gap","question":"Täydennä: 'La semana pasada ___ un intenso debate sobre el tema.'","context":"La semana pasada hubo un intenso debate sobre el tema en el parlamento.","options":["A) hubo","B) había","C) ha habido","D) hay"],"correct":"A","explanation":"Rajattu tapahtuma menneisyydessä → hubo (preteriti haberista). 'Había' olisi tausta (oli käynnissä silloin kun...).","rule":"hubo_vs_habia_e"},
  {"id":4,"type":"gap","question":"Täydennä: 'Vivía en Madrid cuando se ___ la pandemia.'","context":"Vivía en Madrid cuando se declaró la pandemia en marzo de 2020.","options":["A) declaró","B) declaraba","C) ha declarado","D) declara"],"correct":"A","explanation":"Hetkellinen tapahtuma joka keskeytti taustan (vivía) → preteriti. Imperfekti olisi vanhurskas tausta, mikä ei sovi muutospisteeseen.","rule":"imperfecto_cuando_preterito"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · E · pronouns ──────────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'E', 'pronouns', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Me refiero a aquello ___ hablamos ayer.'","context":"Me refiero a aquello de lo que hablamos ayer por la tarde en la cafetería.","options":["A) de lo que","B) que","C) lo que","D) de que"],"correct":"A","explanation":"Prepositio + neutri relatiivi → de lo que. 'Que' yksinään vaatisi edeltävän nominin; 'lo que' ilman prepositiota jättäisi 'hablar de' -rektion kesken.","rule":"de_lo_que_relativo_neutro"},
  {"id":2,"type":"gap","question":"Täydennä: 'No conozco a nadie ___ haya estado allí.'","context":"No conozco a nadie que haya estado allí personalmente en los últimos años.","options":["A) que","B) quien","C) a quien","D) el cual"],"correct":"A","explanation":"Epämäärä antekedentti (nadie) + relatiivi → que + subjunktiivi. 'Quien' käy mutta 'que' on tässä rakenteessa yleisempi.","rule":"nadie_que_subj"},
  {"id":3,"type":"gap","question":"Täydennä: 'Se ___ entregaron los premios a los ganadores.'","context":"Se les entregaron los premios a los ganadores del concurso anual ayer.","options":["A) les","B) los","C) le","D) lo"],"correct":"A","explanation":"Epäsuora monikkoobjekti (a los ganadores) → les. Se-passiivi (se entregaron los premios) + pleonastinen les. 'Los' olisi suora objekti.","rule":"se_les_entregaron"},
  {"id":4,"type":"gap","question":"Täydennä: 'Fue él quien ___ lo dijo primero.'","context":"Fue él quien nos lo dijo primero antes de que lo supiéramos por la prensa.","options":["A) nos","B) le","C) se","D) me"],"correct":"A","explanation":"'Nos lo' = meille sen (monikko 1. p. epäsuora + neutri suora). Oikea järjestys: epäsuora ennen suoraa.","rule":"nos_lo_dijo_orden"}
]$json$::jsonb, 1.0),

('grammar', 'E', 'pronouns', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Lo único ___ importa ahora es tu seguridad.'","context":"Lo único que importa ahora es tu seguridad personal y emocional.","options":["A) que","B) el que","C) lo que","D) cual"],"correct":"A","explanation":"'Lo único' + relatiivi → que (neutri relatiivirakenne 'lo + adj + que'). 'Lo que' olisi redundantti.","rule":"lo_unico_que"},
  {"id":2,"type":"gap","question":"Täydennä: 'El motivo por ___ te escribo es pedirte un favor.'","context":"El motivo por el cual te escribo es pedirte un favor importante.","options":["A) el cual","B) el que","C) que","D) cual"],"correct":"A","explanation":"Prepositio + 'el cual' (muodollinen). 'Por el que' toimii myös (arkisempi), mutta 'por el cual' on E-tason virallinen muoto.","rule":"por_el_cual_formal"},
  {"id":3,"type":"gap","question":"Täydennä: 'Dáse___ a tu hermana cuanto antes.'","context":"Dáselo a tu hermana cuanto antes porque lo necesita para el trabajo.","options":["A) lo","B) le","C) los","D) la"],"correct":"A","explanation":"'Dáselo' = anna se hänelle (imperatiivi + se + lo). Se tulee le:stä + lo:sta (pakollinen muunnos). Painomerkki siirtyy oikealle paikalleen.","rule":"daselo_imperativo_acento"},
  {"id":4,"type":"gap","question":"Täydennä: 'Eso es ___ te quería decir ayer.'","context":"Eso es lo que te quería decir ayer pero no tuve ocasión de hacerlo.","options":["A) lo que","B) que","C) el que","D) cual"],"correct":"A","explanation":"'Eso es lo que' = sitä minä tarkoitin (neutri antekedentti 'eso' → lo que). 'Que' yksinään vaatisi artikkelin.","rule":"eso_es_lo_que"}
]$json$::jsonb, 1.0);
