-- ============================================================
-- Prewarm exercise_bank — L level (laudatur, near-native).
-- Vocab: 7 topics × 2 batches = 14 batches / 56 exercises
-- Grammar: 6 topics × 2 batches = 12 batches / 48 exercises
-- Total: 26 batches / 104 exercises.
-- L-level distractors test idiomatic usage, regional variation, register,
-- literary metaphor, and micro-nuances between near-synonyms that a
-- near-native reader would distinguish.
-- Schema: matches exercise_bank (migrations/008).
-- ============================================================

-- ─── VOCAB · L · general vocabulary ──────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'L', 'general vocabulary', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Sus palabras calaron hondo en el auditorio' — mitä tarkoittaa 'calar hondo'?","context":"Sus palabras calaron hondo en el auditorio que se mantuvo en silencio sepulcral.","options":["A) vaikuttaa syvästi","B) pelotella","C) hämmentää","D) yllättää"],"correct":"A","explanation":"calar hondo = vaikuttaa syvästi (idiomaattinen metafora, 'imeytyä syvälle'). asustar = pelotella, desconcertar = hämmentää, sorprender = yllättää."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'jäädä näpeistään' (epäonnistua)?","context":"El proyecto terminó yéndose al traste por falta de financiación.","options":["A) irse al traste","B) fracasar","C) terminar","D) perder"],"correct":"A","explanation":"irse al traste = mennä pieleen (idiomi). fracasar = epäonnistua (neutraali), terminar = päättyä, perder = menettää. Idiomin kestäminen L-tasolla."},
  {"id":3,"type":"gap","question":"Täydennä: 'El discurso ___ matices difíciles de captar.'","context":"El discurso encierra matices difíciles de captar en una primera lectura.","options":["A) encierra","B) tiene","C) muestra","D) contiene"],"correct":"A","explanation":"encerrar matices = sisältää nyansseja (kirjallinen metafora, 'sulkee sisäänsä'). tener/mostrar/contener ovat neutraaleja. Kirjallinen rekisteri vaatii 'encerrar'."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'dar por sentado'?","context":"No debemos dar por sentado que todo saldrá bien sin esfuerzo.","options":["A) pitää itsestäänselvyytenä","B) toivoa","C) luulla","D) olettaa"],"correct":"A","explanation":"dar por sentado = pitää itsestäänselvänä (idiomi). esperar = toivoa, creer = luulla, suponer = olettaa (lähimmäksi, mutta ei sama sävy)."}
]$json$::jsonb, 1.0),

('vocab', 'L', 'general vocabulary', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Aquella decisión fue un arma de doble filo' — mitä tarkoittaa 'arma de doble filo'?","context":"Aquella decisión fue un arma de doble filo que trajo ventajas e inconvenientes inesperados.","options":["A) kaksiteräinen miekka","B) huono päätös","C) riskialtis valinta","D) ongelma"],"correct":"A","explanation":"arma de doble filo = kaksiteräinen miekka (täsmällinen idiomaattinen vastine). mala decisión = huono päätös (ei idiomi), elección arriesgada = riskialtis valinta, problema = ongelma."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'ottaa kissa pöydälle' (kohdata kiusallinen asia)?","context":"Llegó la hora de poner las cartas sobre la mesa y hablar con franqueza.","options":["A) poner las cartas sobre la mesa","B) hablar claro","C) ser sincero","D) decir la verdad"],"correct":"A","explanation":"poner las cartas sobre la mesa = ottaa kortit pöydälle (idiomaattinen vastine, sama kuvakieli). hablar claro = puhua selvästi (ei idiomi)."},
  {"id":3,"type":"gap","question":"Täydennä: 'Sus intentos ___ en saco roto.'","context":"Sus intentos cayeron en saco roto pese al esfuerzo invertido.","options":["A) cayeron","B) llegaron","C) entraron","D) pasaron"],"correct":"A","explanation":"caer en saco roto = kaatua tyhjiin (idiomi: 'kaatua rikkinäiseen säkkiin'). Vain caer sopii idiomiin — muut verbit eivät luo idiomaattista merkitystä."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'a regañadientes'?","context":"Aceptó la propuesta a regañadientes pero acabó colaborando.","options":["A) vastentahtoisesti","B) mielellään","C) nopeasti","D) hiljaa"],"correct":"A","explanation":"a regañadientes = vastentahtoisesti (idiomaattinen adverbi). de buena gana = mielellään, rápidamente = nopeasti, en silencio = hiljaa."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · L · travel and transport ────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'L', 'travel and transport', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'El viaje se tornó en una odisea inesperada' — mitä tarkoittaa 'tornarse'?","context":"El viaje se tornó en una odisea inesperada tras la cancelación del segundo vuelo.","options":["A) muuttua","B) olla","C) päättyä","D) pitkittyä"],"correct":"A","explanation":"tornarse en = muuttua joksikin (kirjallinen, hieman vanhahtava). convertirse = sama merkitys mutta neutraali, ser = olla, terminar = päättyä. L-tasolla tornarse kirjallinen."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'löytöretki' (metaforisesti)?","context":"Cada viaje es una auténtica andadura que enriquece el espíritu.","options":["A) la andadura","B) el viaje","C) la ruta","D) el camino"],"correct":"A","explanation":"la andadura = vaellus, löytöretki (elämänmatkana, kirjallinen). el viaje = matka, la ruta = reitti, el camino = tie. 'Andadura' kantaa filosofista painoa."},
  {"id":3,"type":"gap","question":"Täydennä: 'Los parajes ___ fueron testigos del paso de los peregrinos.'","context":"Los parajes recónditos fueron testigos del paso de los peregrinos durante siglos.","options":["A) recónditos","B) lejanos","C) aislados","D) bonitos"],"correct":"A","explanation":"recóndito = salaperäinen, syrjäinen (kirjallinen). lejano = kaukainen (geografinen), aislado = eristynyt (fyysinen), bonito = kaunis."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el periplo'?","context":"Su periplo por América Latina duró más de dos años.","options":["A) matkavaellus","B) retki","C) vierailu","D) tutkimus"],"correct":"A","explanation":"el periplo = pitkä matka, kiertomatka (kirjallinen, antiikista). la excursión = retki, la visita = vierailu, la investigación = tutkimus."}
]$json$::jsonb, 1.0),

('vocab', 'L', 'travel and transport', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La caravana avanzaba a duras penas por el desierto' — mitä tarkoittaa 'a duras penas'?","context":"La caravana avanzaba a duras penas por el desierto bajo un sol inclemente.","options":["A) vaivoin","B) nopeasti","C) jatkuvasti","D) varovasti"],"correct":"A","explanation":"a duras penas = vaivoin, töin tuskin (idiomaattinen ilmaus). rápidamente = nopeasti (vastakohta), constantemente = jatkuvasti, con cuidado = varovasti."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'kiemurtelee' (tie)?","context":"El camino serpentea entre colinas hasta llegar al pueblo.","options":["A) serpentear","B) girar","C) pasar","D) moverse"],"correct":"A","explanation":"serpentear = kiemurrella (tie käärmeen tapaan). girar = kääntyä, pasar = kulkea, moverse = liikkua. L-tasolla luontokuvailun sana."},
  {"id":3,"type":"gap","question":"Täydennä: 'El viajero ___ la brújula rota con resignación.'","context":"El viajero contempló la brújula rota con resignación bajo las estrellas.","options":["A) contempló","B) miró","C) vio","D) observó"],"correct":"A","explanation":"contemplar = katsella mietteliäästi (kirjallinen, harras). mirar/ver/observar ovat neutraaleja — contemplar kantaa meditatiivisen sävyn."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la singladura'?","context":"La singladura del barco llegó a su fin en el puerto de Cádiz.","options":["A) merimatka","B) laiva","C) satama","D) kartta"],"correct":"A","explanation":"la singladura = merimatka, purjehduspäivä (merenkulkutermi). el barco = laiva, el puerto = satama, el mapa = kartta. L-taso: erikoissanasto."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · L · health and body ─────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'L', 'health and body', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'El enfermo se recuperó con creces de la operación' — mitä tarkoittaa 'con creces'?","context":"El enfermo se recuperó con creces de la operación tras meses de rehabilitación intensiva.","options":["A) kirkkaasti yli odotusten","B) nopeasti","C) täysin","D) pikkuhiljaa"],"correct":"A","explanation":"con creces = yli odotusten, reilusti (idiomaattinen). rápidamente = nopeasti, completamente = täysin, poco a poco = vähitellen."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'vieri' (taudin)?","context":"El paciente entró en una fase terminal que duró varias semanas.","options":["A) la fase terminal","B) el final","C) la muerte","D) la enfermedad"],"correct":"A","explanation":"la fase terminal = loppuvaihe (lääketieteellinen). el final = loppu (yleinen), la muerte = kuolema, la enfermedad = sairaus."},
  {"id":3,"type":"gap","question":"Täydennä: 'El médico ___ la gravedad del diagnóstico con cautela.'","context":"El médico sopesó la gravedad del diagnóstico con cautela antes de comunicárselo a la familia.","options":["A) sopesó","B) midió","C) vio","D) estudió"],"correct":"A","explanation":"sopesar = punnita (huolellisesti). medir = mitata (konkreettinen), ver = nähdä, estudiar = tutkia. Sopesar kantaa harkinnan merkityksen."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'convalecencia'?","context":"Durante la convalecencia evitó cualquier esfuerzo físico.","options":["A) toipilasaika","B) sairaus","C) hoito","D) lepo"],"correct":"A","explanation":"la convalecencia = toipilasaika (lääketieteellinen). la enfermedad = sairaus, el tratamiento = hoito, el descanso = lepo."}
]$json$::jsonb, 1.0),

('vocab', 'L', 'health and body', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Sus achaques se agudizan con el paso del tiempo' — mitä tarkoittaa 'los achaques'?","context":"Sus achaques se agudizan con el paso del tiempo y ya le impiden dormir bien.","options":["A) ikävaivat","B) sairaus","C) oireet","D) häiriöt"],"correct":"A","explanation":"los achaques = ikävaivat (arkinen mutta kirjallinen, krooniset vaivat erityisesti vanhuudella). la enfermedad = sairaus, los síntomas = oireet, los trastornos = häiriöt."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'kärsivä' (sairaudesta)?","context":"Se trata de un paciente aquejado de una dolencia rara.","options":["A) aquejado de","B) enfermo de","C) con","D) que tiene"],"correct":"A","explanation":"aquejado de = vaivoin kärsivä (kirjallinen). enfermo de = sairas + sairaus (neutraali), con = jolla on, que tiene = jolla on. 'Aquejado' on muodollinen lääketieteellinen."},
  {"id":3,"type":"gap","question":"Täydennä: 'La medicina moderna ___ importantes avances en oncología.'","context":"La medicina moderna ha cosechado importantes avances en oncología durante las últimas décadas.","options":["A) ha cosechado","B) ha tenido","C) ha hecho","D) ha conseguido"],"correct":"A","explanation":"cosechar avances = korjata saavutuksia (maatalousmetafora: 'niittää'). tener/hacer/conseguir ovat neutraaleja. Cosechar kantaa työn palkitseman sävyn."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la postración'?","context":"La postración que siguió al accidente fue profunda y prolongada.","options":["A) masennustila","B) kipu","C) väsymys","D) sairaus"],"correct":"A","explanation":"la postración = täydellinen uupuneisuus, maassa makaaminen (fyysinen + henkinen). el dolor = kipu, el cansancio = väsymys, la enfermedad = sairaus."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · L · society and politics ────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'L', 'society and politics', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La élite política se ha enrocado en sus posturas' — mitä tarkoittaa 'enrocarse'?","context":"La élite política se ha enrocado en sus posturas pese a las evidencias contrarias.","options":["A) linnoittautua","B) piilotella","C) sopia","D) perääntyä"],"correct":"A","explanation":"enrocarse = linnoittautua (alun perin shakkitermi 'enroque'; kuvaannollisesti asenteeseen kiinnittyminen). esconderse = piilotella, acordar = sopia, retroceder = perääntyä."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'pyrkyri' (poliittinen)?","context":"El advenedizo político sorprendió a todos con su rápido ascenso.","options":["A) el advenedizo","B) el nuevo","C) el joven","D) el ambicioso"],"correct":"A","explanation":"el advenedizo = nousukas, äkillinen tulokas (hieman halveksiva). el nuevo/joven ovat neutraaleja, ambicioso = kunnianhimoinen (positiivinen)."},
  {"id":3,"type":"gap","question":"Täydennä: 'El acuerdo ___ el camino hacia una nueva era.'","context":"El acuerdo allanó el camino hacia una nueva era de cooperación internacional.","options":["A) allanó","B) hizo","C) abrió","D) mostró"],"correct":"A","explanation":"allanar el camino = tasoittaa tietä (idiomi). hacer el camino = tehdä tie, abrir = avata (ei yhtä muodollinen), mostrar = näyttää."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el caldo de cultivo'?","context":"La desigualdad crea el caldo de cultivo para el descontento social.","options":["A) otollinen maaperä","B) ongelma","C) syy","D) yhteiskunta"],"correct":"A","explanation":"caldo de cultivo = kasvualusta, otollinen maaperä (idiomaattinen, biologia-metafora). el problema = ongelma, la causa = syy, la sociedad = yhteiskunta."}
]$json$::jsonb, 1.0),

('vocab', 'L', 'society and politics', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'El gobierno ha hecho oídos sordos a las protestas' — mitä tarkoittaa 'hacer oídos sordos'?","context":"El gobierno ha hecho oídos sordos a las protestas ciudadanas durante meses.","options":["A) olla kuulematta","B) vastata","C) sensuroida","D) estää"],"correct":"A","explanation":"hacer oídos sordos = tehdä olevinaan kuuro (idiomi). responder = vastata, censurar = sensuroida, impedir = estää. Suomessa: 'olla kuulematta / kääntää kuuro korvansa'."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'juurruttaa' (yhteiskuntaan)?","context":"Hace falta arraigar los valores democráticos en las generaciones futuras.","options":["A) arraigar","B) enseñar","C) explicar","D) mostrar"],"correct":"A","explanation":"arraigar = juurruttaa (arvot, tavat). enseñar = opettaa, explicar = selittää, mostrar = näyttää. Arraigar on metaforinen (juurtua)."},
  {"id":3,"type":"gap","question":"Täydennä: 'La ley ___ un vacío legal que durante años pasó desapercibido.'","context":"La ley colmó un vacío legal que durante años pasó desapercibido a los legisladores.","options":["A) colmó","B) llenó","C) tapó","D) cerró"],"correct":"A","explanation":"colmar un vacío = täyttää aukko (muodollinen, juridinen). llenar = täyttää (neutraali), tapar = peittää, cerrar = sulkea. Juridisessa kielessä colmar."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el escaparate'?","context":"Las redes sociales se han convertido en el escaparate de nuestra vida.","options":["A) näyteikkuna","B) peili","C) kauppa","D) media"],"correct":"A","explanation":"el escaparate = näyteikkuna (metaforinen: esilläolopaikka). el espejo = peili, la tienda = kauppa, los medios = media."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · L · environment and nature ──────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'L', 'environment and nature', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La naturaleza nos brinda una belleza sobrecogedora' — mitä tarkoittaa 'sobrecogedor'?","context":"La naturaleza nos brinda una belleza sobrecogedora en los atardeceres de montaña.","options":["A) henkeäsalpaava","B) kaunis","C) erityinen","D) epätavallinen"],"correct":"A","explanation":"sobrecogedor = tyrmistävä, henkeäsalpaava (intensiivinen). bonito = kaunis (yleinen), especial = erityinen, inusual = epätavallinen."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'uusiutuminen' (luonnossa)?","context":"El ecosistema muestra una capacidad de resurgir sorprendente tras los incendios.","options":["A) el resurgir","B) la renovación","C) el cambio","D) la recuperación"],"correct":"A","explanation":"el resurgir = uudelleennousu (kirjallinen nominimuoto verbistä 'resurgir'). la renovación = uudistuminen, el cambio = muutos, la recuperación = toipuminen."},
  {"id":3,"type":"gap","question":"Täydennä: 'El paisaje ___ una sinfonía de colores otoñales.'","context":"El paisaje ofrecía una sinfonía de colores otoñales que invitaban a la contemplación.","options":["A) ofrecía","B) tenía","C) mostraba","D) daba"],"correct":"A","explanation":"ofrecer un paisaje = tarjota maisemaa (kirjallinen kollokaatio, 'tarjoaa katseelle'). Muut verbit ovat neutraaleja."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el ocaso'?","context":"El ocaso de las especies endémicas es una tragedia irreversible.","options":["A) sammuminen (loppu)","B) auringonlasku","C) häviäminen","D) kuolema"],"correct":"A","explanation":"el ocaso = loppu, sammuminen (kirjallinen; kirjaim. auringonlasku → kuvaannollisesti). VAROITUS: ocaso voi myös tarkoittaa auringonlaskua — L-tasolla metaforinen käyttö."}
]$json$::jsonb, 1.0),

('vocab', 'L', 'environment and nature', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La biodiversidad se halla en franco retroceso' — mitä tarkoittaa 'en franco retroceso'?","context":"La biodiversidad se halla en franco retroceso en todos los continentes desde 1970.","options":["A) selvästi taantuvana","B) pysähdyksissä","C) muuttumassa","D) katoamassa"],"correct":"A","explanation":"en franco retroceso = selvästi taantuvana (muodollinen ilmaus). en punto muerto = pysähdyksissä, en transformación = muuttumassa, en desaparición = katoamassa."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'köyhdyttää' (maaperä)?","context":"El monocultivo empobrece los suelos de manera irreversible.","options":["A) empobrecer","B) dañar","C) estropear","D) reducir"],"correct":"A","explanation":"empobrecer los suelos = köyhdyttää maaperää (kiinteä maanviljelystermi). dañar = vahingoittaa, estropear = pilata, reducir = vähentää."},
  {"id":3,"type":"gap","question":"Täydennä: 'La fauna ibérica ___ una riqueza insospechada.'","context":"La fauna ibérica atesora una riqueza insospechada de especies endémicas.","options":["A) atesora","B) tiene","C) esconde","D) contiene"],"correct":"A","explanation":"atesorar = kerätä aarteenaan (kirjallinen, 'atesorar' < tesoro). Muut ovat neutraaleja. Atesorar kantaa arvostuksen sävyn."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el erial'?","context":"Aquellas tierras, antaño fértiles, son hoy un erial.","options":["A) joutomaa","B) pelto","C) aavikko","D) metsä"],"correct":"A","explanation":"el erial = joutomaa (viljelemätön, kaunis vanhahtava sana). el campo = pelto, el desierto = aavikko, el bosque = metsä."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · L · culture and arts ────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'L', 'culture and arts', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La novela rezuma melancolía en cada página' — mitä tarkoittaa 'rezumar melancolía'?","context":"La novela rezuma melancolía en cada página y deja un poso difícil de olvidar.","options":["A) tihkua melankoliaa","B) olla surullinen","C) kuvata surua","D) ilmentää tunteita"],"correct":"A","explanation":"rezumar melancolía = tihkua melankoliaa (kirjallinen metafora: 'vuotaa ulos'). ser triste = olla surullinen, describir tristeza = kuvata surua, expresar emociones = ilmentää tunteita."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'kenno' (kirjallinen tyyli)?","context":"Su estilo prosístico presenta una cadencia muy marcada.","options":["A) la cadencia","B) el ritmo","C) el estilo","D) el tono"],"correct":"A","explanation":"la cadencia = rytminen kulku (kirjallinen). el ritmo = rytmi (yleinen), el estilo = tyyli, el tono = sävy. Cadencia sävelmäisempi kuin ritmo."},
  {"id":3,"type":"gap","question":"Täydennä: 'El poeta ___ versos de una belleza arrebatadora.'","context":"El poeta destilaba versos de una belleza arrebatadora en sus últimos años.","options":["A) destilaba","B) escribía","C) hacía","D) creaba"],"correct":"A","explanation":"destilar versos = tislata säkeitä (metafora: keskittää olemus). Muut ovat neutraaleja — destilar kantaa työn ja nautinnon vivahteen."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la posteridad'?","context":"Su obra ha quedado para la posteridad como un testimonio inigualable.","options":["A) jälkipolvet","B) menneisyys","C) historia","D) nykyisyys"],"correct":"A","explanation":"la posteridad = jälkipolvet. el pasado = menneisyys, la historia = historia, el presente = nykyisyys. 'Quedar para la posteridad' on vakiintunut ilmaus."}
]$json$::jsonb, 1.0),

('vocab', 'L', 'culture and arts', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'Su cine se caracteriza por un costumbrismo refinado' — mitä tarkoittaa 'costumbrismo'?","context":"Su cine se caracteriza por un costumbrismo refinado que retrata la España de postguerra.","options":["A) arkitavan kuvaus","B) realismi","C) historiallisuus","D) perinteisyys"],"correct":"A","explanation":"costumbrismo = arkikuvaus (espanjalainen kirjallisuus- ja taidetyyli 1800-luvulta). el realismo = realismi (laajempi), lo histórico = historiallisuus, lo tradicional = perinteisyys. Taidehistorian erikoistermi."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'sovittaa' (teos eri mediumiin)?","context":"La novela fue adaptada al teatro con notable éxito.","options":["A) adaptar","B) cambiar","C) escribir","D) hacer"],"correct":"A","explanation":"adaptar al teatro = sovittaa teatteriin (teatterivakio). cambiar = muuttaa, escribir = kirjoittaa, hacer = tehdä."},
  {"id":3,"type":"gap","question":"Täydennä: 'El ___ de la obra es palpable en el segundo acto.'","context":"El clímax dramático de la obra es palpable en el segundo acto ante los ojos del espectador.","options":["A) clímax","B) final","C) punto","D) medio"],"correct":"A","explanation":"el clímax = huipentuma (draamateoria). el final = loppu, el punto = kohta, el medio = keskikohta. 'Clímax dramático' on E/L-tason taideterminologia."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el mecenas'?","context":"Sin el apoyo de un mecenas generoso, el joven artista no habría sobrevivido.","options":["A) taiteen tukija","B) myyjä","C) opettaja","D) kriitikko"],"correct":"A","explanation":"el mecenas = taidemekenaatti (latinasta, antiikin patronus). el vendedor = myyjä, el maestro = opettaja, el crítico = kriitikko. Kulttuurihistoriallinen erikoistermi."}
]$json$::jsonb, 1.0);

-- ─── VOCAB · L · work and economy ────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('vocab', 'L', 'work and economy', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'El mercado se ha desinflado tras meses de euforia' — mitä tarkoittaa 'desinflarse'?","context":"El mercado bursátil se ha desinflado tras meses de euforia especulativa.","options":["A) puhjeta (kupla)","B) nousta","C) pysähtyä","D) muuttua"],"correct":"A","explanation":"desinflarse = puhjeta, tyhjentyä (metafora: kupla puhkeaa). subir = nousta (vastakohta), pararse = pysähtyä, cambiar = muuttua. Talousuutisten idiomaattinen."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'vipuvaikutus' (rahoituksessa)?","context":"El apalancamiento excesivo puso a la empresa al borde del colapso.","options":["A) el apalancamiento","B) la deuda","C) el préstamo","D) el capital"],"correct":"A","explanation":"el apalancamiento = velkavipu, vipuvoima (rahoitustermi). la deuda = velka, el préstamo = laina, el capital = pääoma. L-tasolla talouspalastan erikoissanasto."},
  {"id":3,"type":"gap","question":"Täydennä: 'La coyuntura actual ___ medidas de calado.'","context":"La coyuntura actual exige medidas de calado para salir de la recesión.","options":["A) exige","B) pide","C) busca","D) necesita"],"correct":"A","explanation":"exigir medidas de calado = vaatia syvällisiä toimia (muodollinen, voimakas). pedir/buscar/necesitar ovat lievempiä. Talouslehdistön vakiintunut exigir."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'la quiebra'?","context":"La quiebra de la empresa dejó a cientos de empleados sin trabajo.","options":["A) konkurssi","B) myyminen","C) sulkeminen","D) muutto"],"correct":"A","explanation":"la quiebra = konkurssi (juridinen). la venta = myynti, el cierre = sulkeminen (ei välttämättä konkurssi), la mudanza = muutto."}
]$json$::jsonb, 1.0),

('vocab', 'L', 'work and economy', 'spanish', $json$[
  {"id":1,"type":"context","question":"Lauseessa 'La empresa capeó la crisis con maniobras audaces' — mitä tarkoittaa 'capear'?","context":"La empresa capeó la crisis con maniobras audaces y una gestión muy astuta.","options":["A) selviytyä (myrskystä)","B) voittaa","C) välttää","D) kestää"],"correct":"A","explanation":"capear = selvitä, ohjata läpi (meritermistä; myrskyn kestäminen). ganar = voittaa, evitar = välttää, soportar = kestää. Capear on erityisen kuvaava idiomi."},
  {"id":2,"type":"translate","question":"Miten sanotaan espanjaksi: 'leimauttaa' (yritys)?","context":"El escándalo estigmatizó a la compañía durante años.","options":["A) estigmatizar","B) marcar","C) dañar","D) afectar"],"correct":"A","explanation":"estigmatizar = leimauttaa (negatiivisesti, pysyvästi). marcar = merkitä, dañar = vahingoittaa, afectar = vaikuttaa. Estigmatizar on voimakkain ja yhteiskunnallisin."},
  {"id":3,"type":"gap","question":"Täydennä: 'Los sindicatos ___ su rechazo a la propuesta.'","context":"Los sindicatos escenificaron su rechazo a la propuesta con una huelga masiva.","options":["A) escenificaron","B) mostraron","C) dijeron","D) hicieron"],"correct":"A","explanation":"escenificar rechazo = lavastaa hylkäys (teatraalinen; julkisen eleen painotus). mostrar/decir/hacer ovat neutraaleja. Journalistisessa kielessä escenificar kantaa näytöksellisyyden."},
  {"id":4,"type":"meaning","question":"¿Qué significa 'el tejido empresarial'?","context":"El tejido empresarial español se compone mayoritariamente de pymes.","options":["A) yrityskenttä","B) tehdas","C) toimisto","D) yritys"],"correct":"A","explanation":"el tejido empresarial = yrityskenttä, yrityskudos (metafora: kudos, jossa yritykset ovat osia). la fábrica = tehdas, la oficina = toimisto, la empresa = yritys."}
]$json$::jsonb, 1.0);

-- ============================================================
-- GRAMMAR · L · 6 topics × 2 batches = 12 batches / 48 exercises
-- ============================================================

-- ─── GRAMMAR · L · ser_estar ─────────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'L', 'ser_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Aquella medida, por radical que ___, no logró frenar la crisis.'","context":"Aquella medida, por radical que fuera, no logró frenar la crisis económica.","options":["A) fuera","B) era","C) fue","D) es"],"correct":"A","explanation":"'Por + adj + que + subjunktiivi' = niin radikaali kuin (se oli)kin. Subjunktiivi pakollinen myönnytyslauseessa. 'Era/fue' rikkoisivat rakenteen.","rule":"por_adj_que_subj_imp"},
  {"id":2,"type":"gap","question":"Täydennä: 'El detalle ___ en que nadie lo había visto.'","context":"El detalle estriba en que nadie lo había visto venir pese a las señales.","options":["A) estriba","B) es","C) está","D) reside"],"correct":"A","explanation":"'Estribar en' = perustua (muodollinen). Tässä ser ei sovi merkityseron vuoksi. 'Residir' olisi synonyymi mutta vähemmän yleinen.","rule":"estribar_en"},
  {"id":3,"type":"gap","question":"Täydennä: 'Ni que decir tiene que la situación ___ insostenible.'","context":"Ni que decir tiene que la situación actual es insostenible a largo plazo.","options":["A) es","B) está","C) hay","D) tiene"],"correct":"A","explanation":"'La situación es insostenible' = luonne. 'Está insostenible' olisi tilapäinen tila — kontekstissa (a largo plazo) pysyvä arvio → ser.","rule":"ser_insostenible_evaluacion"},
  {"id":4,"type":"gap","question":"Täydennä: 'El asunto ___ zanjado desde el pasado martes.'","context":"El asunto queda zanjado desde el pasado martes tras la decisión del comité.","options":["A) queda","B) es","C) está","D) hay"],"correct":"A","explanation":"'Quedar + partisiippi' = jäädä lopulliseen tilaan (sulkeissa). Estar käy myös, mutta quedar on muodollisempi ja korostaa 'lopullisuus'. L-tasolla quedar.","rule":"quedar_zanjado"}
]$json$::jsonb, 1.0),

('grammar', 'L', 'ser_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Los resultados ___ de tal naturaleza que obligaron a replantearse todo.'","context":"Los resultados fueron de tal naturaleza que obligaron a replantearse todo el enfoque del estudio.","options":["A) fueron","B) estuvieron","C) eran","D) estaban"],"correct":"A","explanation":"'Ser de tal naturaleza que' = olivat sellaista luontoa että (rajattu arvio menneisyydessä) → ser preteritissä. Imperfekti/estar muuttaisi merkityksen.","rule":"ser_de_tal_naturaleza"},
  {"id":2,"type":"gap","question":"Täydennä: 'Por lo visto ___ al corriente de todos los detalles.'","context":"Por lo visto está al corriente de todos los detalles de la operación secreta.","options":["A) está","B) es","C) hay","D) tiene"],"correct":"A","explanation":"'Estar al corriente' = olla selvillä (kiinteä muodollinen idiomi). 'Ser al corriente' olisi kielioppivirhe.","rule":"estar_al_corriente"},
  {"id":3,"type":"gap","question":"Täydennä: 'La veracidad de sus afirmaciones ___ puesta en entredicho.'","context":"La veracidad de sus afirmaciones se vio puesta en entredicho tras la investigación.","options":["A) se vio","B) estuvo","C) fue","D) hubo"],"correct":"A","explanation":"'Verse + partisiippi' = tulla (joksikin) (muodollinen). Estar/ser/hubo eivät kanna samaa 'joutua'-sävyä. 'Se vio' on passiivinen refleksi.","rule":"verse_puesto_en_entredicho"},
  {"id":4,"type":"gap","question":"Täydennä: 'Cuanto mayor ___ la dificultad, mayor será el mérito.'","context":"Cuanto mayor sea la dificultad, mayor será el mérito del que logre superarla.","options":["A) sea","B) es","C) será","D) era"],"correct":"A","explanation":"'Cuanto + komp + que + subjunktiivi' = mitä (suurempi) sitä. Suhteuttava rakenne vaatii subjunktiivin epävarmuuden vuoksi.","rule":"cuanto_mas_subj"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · L · hay_estar ─────────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'L', 'hay_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'No ___ quien le siga el paso en el terreno intelectual.'","context":"No hay quien le siga el paso en el terreno intelectual entre sus contemporáneos.","options":["A) hay","B) está","C) es","D) existe"],"correct":"A","explanation":"'No hay quien + subjunktiivi' = ei ole ketään joka (kuvaannollinen: 'kukaan ei pysty'). Kiinteä muodollinen rakenne. Existir olisi kieliopillinen mutta haikeampi.","rule":"no_hay_quien_siga"},
  {"id":2,"type":"gap","question":"Täydennä: 'El proyecto ___ en ciernes cuando se anunció el recorte.'","context":"El proyecto estaba en ciernes cuando se anunció el recorte presupuestario del ministerio.","options":["A) estaba","B) había","C) era","D) existía"],"correct":"A","explanation":"'Estar en ciernes' = olla alkuvaiheessa, vasta ituvaiheessa (kirjallinen idiomi). Haber/ser/existir eivät sovi idiomiin.","rule":"estar_en_ciernes"},
  {"id":3,"type":"gap","question":"Täydennä: 'De ___ alguna pega, habría que señalarla ahora.'","context":"De haber alguna pega en el documento, habría que señalarla ahora antes de la firma.","options":["A) haber","B) estar","C) tener","D) ser"],"correct":"A","explanation":"'De haber + nomini' = jos olisi (hypoteettinen olemassaolo). Vain 'haber' toimii idiomaattisesti hypoteettisena muotona. 'De estar alguna pega' olisi absurdi.","rule":"de_haber_hipotetico"},
  {"id":4,"type":"gap","question":"Täydennä: 'El conflicto ___ latente a pesar del alto el fuego.'","context":"El conflicto permanece latente a pesar del alto el fuego firmado el mes pasado.","options":["A) permanece","B) está","C) es","D) hay"],"correct":"A","explanation":"'Permanecer latente' = pysyä latenttina (muodollinen, muuttumaton tila). 'Está latente' käy, mutta permanecer on täsmällisempi L-tasolla.","rule":"permanecer_latente"}
]$json$::jsonb, 1.0),

('grammar', 'L', 'hay_estar', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'No ___ dudas razonables acerca del veredicto.'","context":"No caben dudas razonables acerca del veredicto emitido por el tribunal.","options":["A) caben","B) hay","C) existen","D) son"],"correct":"A","explanation":"'No caber dudas' = ei ole mahdollista epäillä (muodollinen). 'No hay dudas' käy mutta 'no caben' on muodollisempi + 'razonables' sopii paremmin juridiseen rekisteriin.","rule":"no_caben_dudas"},
  {"id":2,"type":"gap","question":"Täydennä: 'El manuscrito ___ extraviado en el archivo durante décadas.'","context":"El manuscrito yació extraviado en el archivo durante décadas antes de ser redescubierto.","options":["A) yació","B) estuvo","C) fue","D) quedó"],"correct":"A","explanation":"'Yacer' = maata, levätä (kirjallinen, 'olla paikallaan'). Estar/ser/quedar käyvät yleiskielessä mutta L-tasolla kirjallinen yacer paras.","rule":"yacer_extraviado"},
  {"id":3,"type":"gap","question":"Täydennä: 'En estas circunstancias ___ cautos más que nunca.'","context":"En estas circunstancias hay que ser cautos más que nunca con lo que afirmamos.","options":["A) hay que ser","B) es","C) están","D) son"],"correct":"A","explanation":"'Hay que + infinitiivi' = on oltava (impersonaalinen velvoite). Kiinteä muodollinen rakenne. Muut muodot rikkoisivat rakenteen.","rule":"hay_que_ser"},
  {"id":4,"type":"gap","question":"Täydennä: '___ mucho por dilucidar antes del próximo encuentro.'","context":"Queda mucho por dilucidar antes del próximo encuentro con los inversores.","options":["A) Queda","B) Hay","C) Está","D) Es"],"correct":"A","explanation":"'Quedar por + infinitiivi' = on vielä (tekemistä). 'Hay mucho por' käy mutta quedar on muodollisempi ja yleisempi kirjoitetussa tekstissä.","rule":"quedar_por_dilucidar"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · L · subjunctive ───────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'L', 'subjunctive', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Aun a riesgo de que ___ mal, he de decirlo.'","context":"Aun a riesgo de que suene mal, he de decirlo para ser honesto con todos.","options":["A) suene","B) suena","C) sonará","D) sonaba"],"correct":"A","explanation":"'Aun a riesgo de que + subjunktiivi' = vaikkapa uhalla että (epävarmuus). Vakiintunut muodollinen rakenne.","rule":"aun_a_riesgo_de_que_subj"},
  {"id":2,"type":"gap","question":"Täydennä: 'De no ___ por su intervención, el desastre habría sido mayor.'","context":"De no ser por su intervención oportuna, el desastre habría sido mucho mayor.","options":["A) ser","B) sido","C) haber","D) estar"],"correct":"A","explanation":"'De no ser por' = ellei olisi ollut (hypoteettinen kieltorakenne). Kiinteä muoto — muut vaihtoehdot rikkoisivat idiomaattisen kaavan.","rule":"de_no_ser_por"},
  {"id":3,"type":"gap","question":"Täydennä: 'Sea cual ___ la respuesta, la aceptaré.'","context":"Sea cual fuere la respuesta, la aceptaré sin protestar en ningún caso.","options":["A) fuere","B) fuese","C) fuera","D) sea"],"correct":"A","explanation":"'Sea cual fuere' = olipa mikä tahansa (tulevaisuuden subjunktiivi — arkaais, mutta yhä muodollinen). 'Fuese/fuera' ovat yleisempiä. L-tasolla 'fuere' tunnistettava.","rule":"sea_cual_fuere_futuro_subj"},
  {"id":4,"type":"gap","question":"Täydennä: 'Por poco que ___, siempre es mejor que nada.'","context":"Por poco que sea el esfuerzo, siempre es mejor que nada en este tipo de situaciones.","options":["A) sea","B) es","C) será","D) era"],"correct":"A","explanation":"'Por poco que + subjunktiivi' = niin vähän kuin (myönnytys). Subjunktiivi pakollinen.","rule":"por_poco_que_subj"}
]$json$::jsonb, 1.0),

('grammar', 'L', 'subjunctive', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'A menos que ___ algo inesperado, llegaremos a tiempo.'","context":"A menos que suceda algo inesperado, llegaremos a tiempo a la ceremonia de apertura.","options":["A) suceda","B) sucede","C) sucederá","D) sucedió"],"correct":"A","explanation":"'A menos que + subjunktiivi' = ellei (ehto). Subjunktiivi aina.","rule":"a_menos_que_subj"},
  {"id":2,"type":"gap","question":"Täydennä: 'Con tal de que ___ discreción, no diré nada.'","context":"Con tal de que guardes discreción absoluta, no diré nada a los demás miembros del equipo.","options":["A) guardes","B) guardas","C) guardarás","D) guardabas"],"correct":"A","explanation":"'Con tal de que + subjunktiivi' = kunhan (ehdollinen). Subjunktiivi pakollinen ehtolauseissa.","rule":"con_tal_de_que_subj"},
  {"id":3,"type":"gap","question":"Täydennä: 'No hay razón alguna para que ___ tanto tiempo.'","context":"No hay razón alguna para que tarden tanto tiempo en responder a un correo simple.","options":["A) tarden","B) tardan","C) tardaron","D) tardarán"],"correct":"A","explanation":"'Para que + subjunktiivi' (tarkoitus, tässä kieltomuodossa). Subjunktiivi aina para que -rakenteessa.","rule":"no_hay_razon_para_que_subj"},
  {"id":4,"type":"gap","question":"Täydennä: 'Hiciera lo que ___, no lograba satisfacerlo.'","context":"Hiciera lo que hiciese, no lograba satisfacerlo pese a sus enormes esfuerzos.","options":["A) hiciese","B) hacía","C) hacía","D) hiciera"],"correct":"A","explanation":"'Hiciera/hiciese lo que hiciese/hiciera' = teki mitä tahansa (subjunktiivin imperfekti molemmissa muodoissa). Toistuva rakenne muodollinen.","rule":"hiciera_lo_que_hiciese"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · L · conditional ───────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'L', 'conditional', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Yo que él, ___ reconsiderar la propuesta.'","context":"Yo que él, me lo pensaría dos veces antes de reconsiderar la propuesta tan radical.","options":["A) me lo pensaría","B) pienso","C) pensaba","D) lo había pensado"],"correct":"A","explanation":"'Yo que él/tú' + konditionaali = hänen/sinun paikalla tekisin. Vakiintunut neuvonantorakenne.","rule":"yo_que_el_condicional"},
  {"id":2,"type":"gap","question":"Täydennä: '___ hecho lo mismo cualquiera en su lugar.'","context":"Habría hecho lo mismo cualquiera en su lugar ante un dilema tan complicado.","options":["A) Habría","B) Haría","C) Había","D) Habrá"],"correct":"A","explanation":"Irreaalinen menneisyys (kukaan olisi tehnyt) → konditionaalin perfekti. 'Haría' olisi nykyhetki, 'había hecho' indikatiivin pluskvamperfekti.","rule":"habria_hecho_irreal"},
  {"id":3,"type":"gap","question":"Täydennä: 'Si la memoria no me ___, fue un miércoles.'","context":"Si la memoria no me falla, fue un miércoles por la tarde cuando nos conocimos.","options":["A) falla","B) fallara","C) fallaría","D) fallaba"],"correct":"A","explanation":"'Si la memoria no me falla' on kiinteä idiomi indikatiivissa (reaalinen epäilys). 'Fallara' muuttaisi sen hypoteettiseksi — ei idiomaattinen.","rule":"si_la_memoria_no_me_falla_idiom"},
  {"id":4,"type":"gap","question":"Täydennä: 'De haber tenido más presupuesto, la película ___ grande.'","context":"De haber tenido más presupuesto, la película habría sido más grande a todos los niveles.","options":["A) habría sido","B) sería","C) era","D) fue"],"correct":"A","explanation":"'De haber + partisiippi' (menneisyyden hypoteesi) → konditionaalin perfekti. 'Sería' on yksinkertainen konditionaali = nykyhetki, ei sovi menneeseen ehtoon.","rule":"de_haber_tenido_habria_sido"}
]$json$::jsonb, 1.0),

('grammar', 'L', 'conditional', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Uno ___ pensar que todo está bajo control.'","context":"Uno diría pensar que todo está bajo control, pero los hechos demuestran lo contrario.","options":["A) diría","B) dice","C) decía","D) dijo"],"correct":"A","explanation":"'Uno diría' = yleistävä arvio ('voisi sanoa'), muodollinen konditionaali. 'Dice' olisi suora väite.","rule":"uno_diria_generico"},
  {"id":2,"type":"gap","question":"Täydennä: 'Sería de esperar que ___ más transparencia.'","context":"Sería de esperar que hubiera más transparencia en este tipo de procesos.","options":["A) hubiera","B) hay","C) habrá","D) había"],"correct":"A","explanation":"'Ser de esperar que + subjunktiivin imperfekti' (toive). Konditionaali pääverbissä + subjunktiivi sivulauseessa. 'Hay' olisi indikatiivi ja rikkoisi konkordanssin.","rule":"seria_de_esperar_que"},
  {"id":3,"type":"gap","question":"Täydennä: 'Cabría preguntarse si ___ realmente necesario.'","context":"Cabría preguntarse si es realmente necesario un cambio tan drástico en esta fase.","options":["A) es","B) sea","C) fuera","D) era"],"correct":"A","explanation":"'Cabría preguntarse si + indikatiivi' (epäsuora kysymys 'si' = onko). 'Si' epäsuorassa kysymyksessä EI laukaise subjunktiivia, toisin kuin ehto-si.","rule":"si_indirecto_indicativo"},
  {"id":4,"type":"gap","question":"Täydennä: 'Dijo que ___ para ayudar, pero nunca apareció.'","context":"Dijo que vendría para ayudar con la mudanza, pero nunca apareció aquel día.","options":["A) vendría","B) venía","C) vino","D) viene"],"correct":"A","explanation":"Menneisyyden tulevaisuus raportoidussa puheessa → konditionaali. 'Venía' olisi imperfekti (yleensä tuli), 'vino' preteriti (tuli).","rule":"condicional_discurso_indirecto_l"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · L · preterite_imperfect ───────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'L', 'preterite_imperfect', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Jamás ___ una cosa igual en treinta años de carrera.'","context":"Jamás había visto una cosa igual en treinta años de carrera profesional.","options":["A) había visto","B) vi","C) veía","D) he visto"],"correct":"A","explanation":"'Jamás + pluskvamperfekti' = en ollut koskaan aiemmin nähnyt (ennen nykyhetkeä menneisyydessä). Preteriti ei sovi 'jamás + años' -rakenteeseen.","rule":"jamas_habia_visto"},
  {"id":2,"type":"gap","question":"Täydennä: 'Cuando ___ de la reunión, llovía a cántaros.'","context":"Cuando salimos de la reunión, llovía a cántaros y apenas se veía la calle.","options":["A) salimos","B) salíamos","C) hemos salido","D) salíamos"],"correct":"A","explanation":"'Cuando + preteriti' = hetkellinen poistuminen (tapahtuma). Imperfekti 'salíamos' olisi toistuvaa taustaa — ei sovi 'cuando' + rinnakkainen tapahtuma.","rule":"cuando_preterito_llovia"},
  {"id":3,"type":"gap","question":"Täydennä: 'Aquella tarde ___ a menudo, como si supiera algo.'","context":"Aquella tarde sonreía a menudo, como si supiera algo que los demás ignorábamos.","options":["A) sonreía","B) sonrió","C) ha sonreído","D) sonríe"],"correct":"A","explanation":"Toistuva toiminta taustana ('a menudo' = usein) → imperfekti. Preteriti olisi yksittäinen hetki.","rule":"a_menudo_imperfecto"},
  {"id":4,"type":"gap","question":"Täydennä: 'En aquel instante ___ todo lo que había pasado.'","context":"En aquel instante comprendí todo lo que había pasado durante los últimos meses.","options":["A) comprendí","B) comprendía","C) he comprendido","D) comprendo"],"correct":"A","explanation":"Tajuamisen hetki (muutospiste) → preteriti. 'Comprendía' olisi jatkuva ymmärtäminen, mikä ei sovi 'en aquel instante':n kanssa.","rule":"comprender_preterito_instante"}
]$json$::jsonb, 1.0),

('grammar', 'L', 'preterite_imperfect', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Conoció a su esposa mientras ___ la tesis en París.'","context":"Conoció a su esposa mientras escribía la tesis en París, en una cafetería del Barrio Latino.","options":["A) escribía","B) escribió","C) ha escrito","D) escribe"],"correct":"A","explanation":"'Mientras + imperfekti' = samanaikainen kestotoiminta. 'Conoció' (preteriti) on hetkellinen muutos tausta-toiminnan aikana.","rule":"mientras_escribia_conocio"},
  {"id":2,"type":"gap","question":"Täydennä: 'Llevaba cinco años casado cuando ___ el cáncer.'","context":"Llevaba cinco años casado cuando le diagnosticaron el cáncer de forma inesperada.","options":["A) le diagnosticaron","B) le diagnosticaban","C) le ha diagnosticado","D) le diagnostican"],"correct":"A","explanation":"Hetkellinen tapahtuma kesto-taustalla ('llevaba 5 años') → preteriti. Imperfekti olisi toistuva diagnoosi — absurdi.","rule":"llevaba_diagnosticaron"},
  {"id":3,"type":"gap","question":"Täydennä: 'Solía ir al cine todos los jueves, pero una tarde ___ de idea.'","context":"Solía ir al cine todos los jueves, pero una tarde cambió de idea y se fue al teatro.","options":["A) cambió","B) cambiaba","C) ha cambiado","D) cambia"],"correct":"A","explanation":"Tapa (solía) katkeaa yksittäiseen muutospisteeseen → preteriti. Imperfekti 'cambiaba' olisi myös tapa (ristiriita).","rule":"solia_cambio_preterito"},
  {"id":4,"type":"gap","question":"Täydennä: 'Cada vez que ___ a la ciudad, visitaba ese mismo café.'","context":"Cada vez que iba a la ciudad, visitaba ese mismo café en la Plaza Mayor.","options":["A) iba","B) fui","C) he ido","D) voy"],"correct":"A","explanation":"'Cada vez que' + toistuva toiminta → imperfekti molemmissa verbeissä (iba + visitaba). Preteriti olisi yksittäinen matka.","rule":"cada_vez_que_imperfecto"}
]$json$::jsonb, 1.0);

-- ─── GRAMMAR · L · pronouns ──────────────────────────────────
INSERT INTO exercise_bank (mode, level, topic, language, payload, quality_score) VALUES
('grammar', 'L', 'pronouns', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: '___ me consta que todavía queda mucho por hacer.'","context":"A mí me consta que todavía queda mucho por hacer antes de cerrar el proyecto.","options":["A) A mí","B) Yo","C) Me","D) Mí"],"correct":"A","explanation":"'Constar' on 'gustar'-tyypin verbi (dat-verbi) → painottava 'a mí' + pakollinen 'me'. 'Yo me consta' on virhe.","rule":"a_mi_me_consta_dat"},
  {"id":2,"type":"gap","question":"Täydennä: 'El libro, ___ autor desconozco, es un clásico.'","context":"El libro, cuyo autor desconozco por completo, es considerado un clásico en su género.","options":["A) cuyo","B) que","C) del que","D) el cual"],"correct":"A","explanation":"Omistusrelatiivi (sen kirjoittaja) → cuyo. Maskuliini 'autor' → cuyo (ei cuya). 'Del que' olisi 'josta' (eri merkitys).","rule":"cuyo_autor_posesion"},
  {"id":3,"type":"gap","question":"Täydennä: 'Aquel es el momento del ___ siempre guardará un recuerdo amargo.'","context":"Aquel es el momento del que siempre guardará un recuerdo amargo de su infancia.","options":["A) que","B) cual","C) cuyo","D) el que"],"correct":"A","explanation":"Prepositio + neutri relatiivi → del que. 'Del cual' toimii myös mutta 'del que' on yleisempi. Cuyo ei sovi (ei omistuksesta)","rule":"del_que_prep_neutro"},
  {"id":4,"type":"gap","question":"Täydennä: 'Diose ___ por vencido tras tantos intentos fallidos.'","context":"Diose por vencido tras tantos intentos fallidos y se retiró definitivamente.","options":["A) —","B) se","C) le","D) lo"],"correct":"A","explanation":"'Diose' = dio + se (kirjallinen vanhahtava enklittinen muoto). Pronomini on JO liitetty verbiin ('diose'), ei enää toista. L-tasolla tämä harvinainen muoto tunnistettava.","rule":"diose_enclitico_antiguo"}
]$json$::jsonb, 1.0),

('grammar', 'L', 'pronouns', 'spanish', $json$[
  {"id":1,"type":"gap","question":"Täydennä: 'Ahí es ___ radica el verdadero problema.'","context":"Ahí es donde radica el verdadero problema de la organización en los últimos años.","options":["A) donde","B) que","C) cuando","D) lo que"],"correct":"A","explanation":"'Ahí es donde' = siinä on kohta jossa (paikan relatiivi). Que olisi neutraali, cuando ajan, lo que neutri — vain donde sopii.","rule":"ahi_es_donde"},
  {"id":2,"type":"gap","question":"Täydennä: 'No son pocos ___ opinan lo contrario.'","context":"No son pocos los que opinan lo contrario sobre este tema tan controvertido.","options":["A) los que","B) quienes","C) que","D) los cuales"],"correct":"A","explanation":"'Los que/quienes' = ne jotka. Molemmat toimivat mutta 'los que' on tavallisempi puheessa. L-tasolla molemmat tunnistettava. 'Que' yksinään vaatisi edeltävän nominin.","rule":"los_que_quienes"},
  {"id":3,"type":"gap","question":"Täydennä: 'A fuerza de insistir ___ convenció finalmente.'","context":"A fuerza de insistir lo convenció finalmente tras semanas de debate.","options":["A) lo","B) le","C) se","D) la"],"correct":"A","explanation":"'Convencer a alguien' = suora objekti (a + henkilö, mutta pronominina 'lo/la'). 'Le' olisi leísmo (Espanjassa hyväksytty maskul., mutta normatiivi = 'lo').","rule":"convencer_lo_leismo"},
  {"id":4,"type":"gap","question":"Täydennä: '___ llamen o no, da igual: ya no pienso responder.'","context":"Me llamen o no, da igual: ya no pienso responder a nadie sobre ese asunto.","options":["A) Me","B) A mí","C) Yo","D) Mí"],"correct":"A","explanation":"'Me llamen o no' = soittavatpa minulle tai ei (subjunktiivi + klitti). Pakollinen 'me' (verbin dat-objekti). 'A mí' ilman 'me' olisi keskeneräinen.","rule":"me_llamen_o_no_clitico"}
]$json$::jsonb, 1.0);
